# Generated by Django 5.1.4 on 2025-03-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_billtype'),
        ('OnBoard', '0067_batchreport_output_file_alter_batchreport_table'),
        ('Report', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report_billed_data',
            unique_together={('company', 'organization', 'vendor', 'Account_Number', 'Month', 'Year')},
        ),
    ]
