# Generated by Django 5.1.4 on 2025-03-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0002_alter_report_billed_data_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report_billed_data',
            unique_together=set(),
        ),
    ]
