# Generated by Django 5.1.4 on 2025-03-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0003_alter_report_billed_data_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downloaded_reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(blank=True, max_length=255, null=True)),
                ('kwargs', models.JSONField(default=dict)),
                ('file', models.FileField(upload_to='DownloadedExcelReports/')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'DownloadedReports',
            },
        ),
    ]
