# Generated by Django 5.1.4 on 2025-08-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(help_text='Organization id from external source/UI')),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('specific', 'Specific')], max_length=16)),
                ('days', models.JSONField(default=list)),
                ('emails', models.JSONField(default=list)),
                ('created_by_id', models.IntegerField(blank=True, null=True)),
                ('created_by_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
