# Generated by Django 5.1.4 on 2025-08-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0002_emailconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfiguration',
            name='use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
