# Generated by Django 5.1.4 on 2025-08-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0003_emailconfiguration_use_ssl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfiguration',
            name='use_tls',
            field=models.BooleanField(default=False),
        ),
    ]
