# Generated by Django 5.1.4 on 2025-08-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0004_alter_emailconfiguration_use_tls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchautomation',
            name='emails',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
