# Generated by Django 5.1.4 on 2025-08-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0006_alter_batchautomation_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchautomation',
            name='emails',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
