# Generated by Django 5.1.4 on 2025-08-29 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0007_alter_batchautomation_emails'),
        ('OnBoard', '0148_rename_inventort_basedatatable_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfiguration',
            name='sub_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_configuration', to='OnBoard.organizations'),
        ),
    ]
