# Generated by Django 5.1.4 on 2025-09-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0008_emailconfiguration_sub_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(db_index=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
