# Generated by Django 5.1.4 on 2025-09-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0009_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='company_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='company',
            field=models.CharField(default='OneSmarter', max_length=255),
        ),
    ]
