# Generated by Django 5.1.4 on 2025-09-11 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0010_remove_notification_company_id_notification_company'),
        ('OnBoard', '0152_alter_organizations_domain_alter_organizations_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchautomation',
            name='sub_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_automation', to='OnBoard.organizations'),
        ),
        migrations.AddField(
            model_name='notification',
            name='company_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_notifications', to='OnBoard.company'),
        ),
    ]
