# Generated by Django 5.1.4 on 2025-10-10 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0012_notification_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notification',
            table='Notification',
        ),
    ]
