# Generated by Django 5.1.4 on 2025-10-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0013_alter_notification_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
