# Generated by Django 5.1.4 on 2025-12-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0014_alter_notification_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchautomation',
            name='days',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
