# Generated by Django 5.1.4 on 2025-12-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0015_alter_batchautomation_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchautomation',
            name='days',
            field=models.JSONField(default=list),
        ),
    ]
