# Generated by Django 5.1.4 on 2025-12-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0016_alter_batchautomation_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchautomation',
            name='dates',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='batchautomation',
            name='days',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
