# Generated by Django 5.1.4 on 2025-01-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='ManuallyAddedCompany',
        ),
        migrations.AlterModelTable(
            name='manuallyaddedcompany',
            table='ManuallyAddedCompany',
        ),
    ]
