# Generated by Django 5.1.4 on 2025-01-17 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_rename_company_manuallyaddedcompany_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='ManuallyAddedLocation',
        ),
        migrations.AlterModelTable(
            name='manuallyaddedlocation',
            table='ManuallyAddedLocation',
        ),
    ]
