# Generated by Django 5.1.4 on 2025-03-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_billtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='company_overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendors',
            name='customer_portal_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendors',
            name='customer_support_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendors',
            name='customer_support_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendors',
            name='features',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vendors',
            name='home_page',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendors',
            name='pricing',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vendors',
            name='reliability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vendors',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendors',
            name='support',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vendors',
            name='user_friendly',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vendors',
            name='vendor_logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_logos/'),
        ),
    ]
