# Generated by Django 5.1.4 on 2025-04-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_vendors_company_overview_vendors_customer_portal_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, null=True, unique=True)),
                ('sub_categories', models.JSONField(default=list, null=True)),
            ],
            options={
                'db_table': 'BaselineCategories',
            },
        ),
    ]
