# Generated by Django 5.1.4 on 2025-04-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_baselinecategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselinecategories',
            name='category',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
