# Generated by Django 5.1.4 on 2025-04-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0008_alter_baselinecategories_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='ratings',
            field=models.FloatField(default=0.0),
        ),
    ]
