# Generated by Django 5.1.4 on 2025-04-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0010_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='usertype',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
