# Generated by Django 5.1.4 on 2025-04-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0012_alter_profile_phone_profile_unique_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='permissions', to='Dashboard.permission'),
        ),
    ]
