# Generated by Django 5.1.4 on 2025-04-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0014_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='usertype',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
