# Generated by Django 5.1.4 on 2025-05-03 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0015_alter_profile_usertype'),
        ('OnBoard', '0115_alter_basedatatable_billingadd_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=255)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('suspend_forward_date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reuqest_organizations', to='OnBoard.organizations')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reuqest_users', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reuqest_vendors', to='Dashboard.vendors')),
            ],
            options={
                'db_table': 'Requests',
            },
        ),
    ]
