# Generated by Django 5.1.4 on 2025-05-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0016_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='suspend_forward_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
