# Generated by Django 5.1.4 on 2025-05-05 04:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0018_requests_ban_requests_business_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='request_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
