# Generated by Django 5.1.4 on 2025-05-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0019_requests_created_requests_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='area_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='is_insurace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requests',
            name='is_international_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requests',
            name='is_voice_calling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requests',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
