# Generated by Django 5.1.4 on 2025-05-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0022_alter_requests_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='authorized_party',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='contact_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='current_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='device_cost',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='forward_to_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='forward_to_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='is_call_forwarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requests',
            name='is_new_device',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requests',
            name='is_susped_30_days',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requests',
            name='other_documents',
            field=models.FileField(blank=True, null=True, upload_to='Requests_documents'),
        ),
        migrations.AddField(
            model_name='requests',
            name='port_pin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='resume_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='support_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='upgrade_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
