# Generated by Django 5.1.4 on 2025-05-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0023_requests_authorized_party_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='line_of_service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
