# Generated by Django 5.1.4 on 2025-05-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0024_requests_line_of_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='cancel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='forward_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
