# Generated by Django 5.1.4 on 2025-06-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0026_alter_requests_cancel_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='is_insurace',
            new_name='is_insurance',
        ),
    ]
