# Generated by Django 5.1.4 on 2025-06-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0027_rename_is_insurace_requests_is_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
