# Generated by Django 5.1.4 on 2025-07-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0028_requests_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('Tablet', 'Tablet'), ('Smartphone', 'Smartphone')], max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=255, null=True)),
                ('amount', models.FloatField(default=0)),
                ('is_older_model', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'Device',
            },
        ),
    ]
