# Generated by Django 5.1.4 on 2025-07-02 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0029_device'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
