# Generated by Django 5.1.4 on 2025-07-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0031_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='os',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
