# Generated by Django 5.1.4 on 2025-07-02 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0032_alter_device_os'),
        ('OnBoard', '0133_basedatatable_net_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('Tablet', 'Tablet'), ('Smartphone', 'Smartphone')], max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('sub_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_company_approved_devices', to='OnBoard.organizations')),
            ],
            options={
                'db_table': 'ApprovedDevice',
            },
        ),
    ]
