# Generated by Django 5.1.4 on 2025-07-02 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0034_endoflifedevice'),
        ('OnBoard', '0133_basedatatable_net_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='is_damaged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='repair_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DamagedDevicePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('Tablet', 'Tablet'), ('Smartphone', 'Smartphone')], max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('estimted_cost', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('sub_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_company_damaged_devices', to='OnBoard.organizations')),
            ],
            options={
                'db_table': 'DamagedDevicePolicy',
            },
        ),
    ]
