# Generated by Django 5.1.4 on 2025-07-04 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0035_device_is_approved_device_is_damaged_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damageddevicepolicy',
            name='sub_company',
        ),
        migrations.RemoveField(
            model_name='endoflifedevice',
            name='sub_company',
        ),
        migrations.DeleteModel(
            name='ApprovedDevice',
        ),
        migrations.DeleteModel(
            name='DamagedDevicePolicy',
        ),
        migrations.DeleteModel(
            name='EndofLifeDevice',
        ),
    ]
