# Generated by Django 5.1.4 on 2025-07-04 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0036_remove_damageddevicepolicy_sub_company_and_more'),
        ('OnBoard', '0133_basedatatable_net_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('storage', models.CharField(blank=True, max_length=10, null=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('sub_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_company_models', to='OnBoard.organizations')),
            ],
            options={
                'db_table': 'MakeModel',
                'constraints': [models.UniqueConstraint(fields=('sub_company', 'device_type', 'name'), name='unique_model')],
            },
        ),
    ]
