# Generated by Django 5.1.4 on 2025-07-04 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0037_makemodel'),
        ('OnBoard', '0133_basedatatable_net_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('retail_price', models.FloatField(default=0)),
                ('discounted_price', models.FloatField(default=0)),
                ('is_payment_plan', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('sub_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_company_vendor_devices', to='OnBoard.organizations')),
            ],
            options={
                'db_table': 'VendorDevice',
            },
        ),
        migrations.CreateModel(
            name='VendorInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=255)),
                ('ban', models.CharField(max_length=20)),
                ('plan', models.CharField(max_length=255)),
                ('plan_type', models.CharField(max_length=255)),
                ('data_allotment', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_fee', models.FloatField(default=0)),
                ('smartphone', models.FloatField(default=0)),
                ('tablet_computer', models.FloatField(default=0)),
                ('mifi', models.FloatField(default=0)),
                ('wearables', models.FloatField(default=0)),
                ('sales_rep_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sales_rep_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('sales_rep_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('tech_support_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('tech_support_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('order_support_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('single_point_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('is_international_plan', models.BooleanField(default=False)),
                ('is_voip_calling', models.BooleanField(default=False)),
                ('is_insurance', models.BooleanField(default=False)),
                ('baselines_object', models.JSONField(default=list)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('sub_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_company_vendor_info', to='OnBoard.organizations')),
            ],
            options={
                'db_table': 'VendorInformation',
                'constraints': [models.UniqueConstraint(fields=('sub_company', 'vendor', 'ban', 'plan'), name='unique_vendor_information')],
            },
        ),
    ]
