# Generated by Django 5.1.4 on 2025-07-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0038_vendordevice_vendorinformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorinformation',
            old_name='baselines_object',
            new_name='baseline_object',
        ),
    ]
