# Generated by Django 5.1.4 on 2025-07-08 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0040_requests_comment_requests_cost_center_add_and_more'),
        ('OnBoard', '0133_basedatatable_net_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban', models.CharField(max_length=255)),
                ('cost_center', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('sub_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_company_costcenters', to='OnBoard.organizations')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_costcenters', to='Dashboard.vendors')),
            ],
            options={
                'db_table': 'CostCenters',
                'constraints': [models.UniqueConstraint(fields=('sub_company', 'vendor', 'ban', 'cost_center'), name='unique_cost_center')],
            },
        ),
    ]
