# Generated by Django 5.1.4 on 2025-07-09 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0041_costcenters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='Dashboard.makemodel'),
        ),
    ]
