# Generated by Django 5.1.4 on 2025-07-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0042_alter_device_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_individual_purchase',
            field=models.BooleanField(default=False),
        ),
    ]
