# Generated by Django 5.1.4 on 2025-07-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0043_device_is_individual_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='order_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='reorder_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
