# Generated by Django 5.1.4 on 2025-07-10 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0044_device_order_quantity_device_reorder_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendordevice',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_device_models', to='Dashboard.makemodel'),
        ),
        migrations.AlterField(
            model_name='vendordevice',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_devices', to='Dashboard.vendors'),
        ),
        migrations.AlterField(
            model_name='vendorinformation',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_information', to='Dashboard.vendors'),
        ),
    ]
