# Generated by Django 5.1.4 on 2025-07-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0045_alter_vendordevice_model_alter_vendordevice_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinformation',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendorinformation',
            name='plan_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
