# Generated by Django 5.1.4 on 2025-07-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0046_vendorinformation_is_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='os',
        ),
        migrations.AddField(
            model_name='makemodel',
            name='os',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
