# Generated by Django 5.1.4 on 2025-07-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0047_remove_device_os_makemodel_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinformation',
            name='request_file',
            field=models.FileField(blank=True, null=True, upload_to='vendor_information_files'),
        ),
        migrations.AddField(
            model_name='vendorinformation',
            name='request_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
