# Generated by Django 5.1.4 on 2025-07-11 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0048_vendorinformation_request_file_and_more'),
        ('OnBoard', '0133_basedatatable_net_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban', models.CharField(max_length=20)),
                ('plan', models.CharField(max_length=255)),
                ('plan_type', models.CharField(blank=True, max_length=255, null=True)),
                ('data_allotment', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_fee', models.FloatField(default=0)),
                ('smartphone', models.FloatField(default=0)),
                ('tablet_computer', models.FloatField(default=0)),
                ('mifi', models.FloatField(default=0)),
                ('wearables', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'VendorPlan',
            },
        ),
        migrations.RemoveConstraint(
            model_name='vendorinformation',
            name='unique_vendor_information',
        ),
        migrations.RemoveField(
            model_name='vendorinformation',
            name='data_allotment',
        ),
        migrations.RemoveField(
            model_name='vendorinformation',
            name='mifi',
        ),
        migrations.RemoveField(
            model_name='vendorinformation',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='vendorinformation',
            name='plan_fee',
        ),
        migrations.RemoveField(
            model_name='vendorinformation',
            name='plan_type',
        ),
        migrations.RemoveField(
            model_name='vendorinformation',
            name='smartphone',
        ),
        migrations.RemoveField(
            model_name='vendorinformation',
            name='tablet_computer',
        ),
        migrations.RemoveField(
            model_name='vendorinformation',
            name='wearables',
        ),
        migrations.AddField(
            model_name='vendorplan',
            name='sub_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_company_vendor_plans', to='OnBoard.organizations'),
        ),
        migrations.AddField(
            model_name='vendorplan',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_plans', to='Dashboard.vendors'),
        ),
        migrations.AddField(
            model_name='vendorinformation',
            name='vendor_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_information_plans', to='Dashboard.vendorplan'),
        ),
        migrations.AddConstraint(
            model_name='vendorinformation',
            constraint=models.UniqueConstraint(fields=('sub_company', 'vendor', 'ban', 'vendor_plan'), name='unique_vendor_information'),
        ),
        migrations.AddConstraint(
            model_name='vendorplan',
            constraint=models.UniqueConstraint(fields=('sub_company', 'vendor', 'ban', 'plan', 'plan_type'), name='unique_vendor_plan'),
        ),
    ]
