# Generated by Django 5.1.4 on 2025-07-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0049_vendorplan_and_more'),
        ('OnBoard', '0133_basedatatable_net_amount'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vendorplan',
            name='unique_vendor_plan',
        ),
        migrations.AddConstraint(
            model_name='vendorplan',
            constraint=models.UniqueConstraint(fields=('sub_company', 'vendor', 'ban', 'plan'), name='unique_vendor_plan'),
        ),
    ]
