# Generated by Django 5.1.4 on 2025-07-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0050_remove_vendorplan_unique_vendor_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinformation',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
