# Generated by Django 5.1.4 on 2025-07-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0051_vendorinformation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinformation',
            name='existing_plan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
