# Generated by Django 5.1.4 on 2025-07-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0052_vendorinformation_existing_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinformation',
            name='plan_replaced_with',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
