# Generated by Django 5.1.4 on 2025-07-15 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0053_vendorinformation_plan_replaced_with'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_details', models.CharField(blank=True, max_length=255, null=True)),
                ('wipe_reset_firmware', models.CharField(blank=True, max_length=255, null=True)),
                ('name_change', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_activity', models.CharField(blank=True, max_length=255, null=True)),
                ('device_status', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request_tracking_info', to='Dashboard.requests')),
            ],
            options={
                'db_table': 'TrackingInfo',
            },
        ),
    ]
