# Generated by Django 5.1.4 on 2025-07-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0054_trackinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinginfo',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='request_tracking_files'),
        ),
    ]
