# Generated by Django 5.1.4 on 2025-07-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0055_trackinginfo_receipt_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinginfo',
            name='shipment_vendor',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='trackinginfo',
            name='device_status',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
