# Generated by Django 5.1.4 on 2025-07-15 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0056_trackinginfo_shipment_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinginfo',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_tracking_info', to='Dashboard.requests'),
        ),
    ]
