# Generated by Django 5.1.4 on 2025-07-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0057_alter_trackinginfo_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='tracking_id',
        ),
        migrations.AddField(
            model_name='trackinginfo',
            name='tracking_id',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
