# Generated by Django 5.1.4 on 2025-07-16 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0058_remove_requests_tracking_id_trackinginfo_tracking_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrackingInfo',
        ),
    ]
