# Generated by Django 5.1.4 on 2025-07-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0060_trackinginfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinginfo',
            name='tracking_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
