# Generated by Django 5.1.4 on 2025-07-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0061_alter_trackinginfo_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinginfo',
            name='shipment_vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trackinginfo',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
