# Generated by Django 5.1.4 on 2025-08-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0062_alter_trackinginfo_shipment_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='company_overview',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='customer_portal_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='customer_support_email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='customer_support_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='home_page',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='review',
            field=models.TextField(blank=True, default=''),
        ),
    ]
