# Generated by Django 5.1.4 on 2025-08-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0063_alter_vendors_company_overview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
