# Generated by Django 5.1.4 on 2025-08-19 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0064_requests_tracking_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='tracking_id',
            new_name='request_tracking_id',
        ),
    ]
