# Generated by Django 5.1.4 on 2025-08-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0065_rename_tracking_id_requests_request_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vendors',
            field=models.ManyToManyField(related_name='profile_vendors', to='Dashboard.vendors'),
        ),
    ]
