# Generated by Django 5.1.4 on 2025-08-27 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0067_alter_profile_phone'),
        ('OnBoard', '0146_remove_basedatatable_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselinecategories',
            name='ban',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='baselinecategories',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories_organizations', to='OnBoard.organizations'),
        ),
        migrations.AddField(
            model_name='baselinecategories',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories_vendors', to='Dashboard.vendors'),
        ),
    ]
