# Generated by Django 5.1.4 on 2025-08-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0068_baselinecategories_ban_and_more'),
        ('OnBoard', '0146_remove_basedatatable_inventory_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='baselinecategories',
            unique_together={('organization', 'vendor', 'ban', 'category')},
        ),
    ]
