# Generated by Django 5.1.4 on 2025-08-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0069_alter_baselinecategories_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vendors',
            field=models.ManyToManyField(null=True, related_name='profile_vendors', to='Dashboard.vendors'),
        ),
    ]
