# Generated by Django 5.1.4 on 2025-08-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0071_alter_profile_vendors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselinecategories',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vendors',
            field=models.ManyToManyField(blank=True, related_name='profile_vendors', to='Dashboard.vendors'),
        ),
    ]
