# Generated by Django 5.1.4 on 2025-09-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0072_alter_baselinecategories_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotChats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=255)),
                ('question', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'BotChats',
            },
        ),
    ]
