# Generated by Django 5.1.4 on 2025-09-10 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0073_botchats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotChats',
        ),
    ]
