# Generated by Django 5.1.4 on 2025-09-18 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0010_analysisdata_multiple_analysis'),
        ('Dashboard', '0075_botchats'),
    ]

    operations = [
        migrations.AddField(
            model_name='botchats',
            name='analysisChat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_chats', to='Analysis.multiplefileupload'),
        ),
    ]
