# Generated by Django 5.1.4 on 2025-09-19 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0010_analysisdata_multiple_analysis'),
        ('Dashboard', '0076_botchats_analysischat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botchats',
            name='analysisChat',
        ),
        migrations.AddField(
            model_name='botchats',
            name='M_analysisChat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M_analysis_chats', to='Analysis.multiplefileupload'),
        ),
        migrations.AddField(
            model_name='botchats',
            name='S_analysisChat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='S_analysis_chats', to='Analysis.analysis'),
        ),
    ]
