# Generated by Django 5.1.4 on 2025-09-22 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0016_summarydata'),
        ('Dashboard', '0078_botchats_billchat_alter_botchats_s_analysischat'),
        ('View', '0021_alter_contracts_contract_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botchats',
            name='S_analysisChat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='S_analysis_chats', to='Analysis.analysis'),
        ),
        migrations.AlterField(
            model_name='botchats',
            name='billChat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_chats', to='View.viewuploadbill'),
        ),
    ]
