# Generated by Django 5.1.4 on 2025-09-22 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0079_alter_botchats_s_analysischat_and_more'),
        ('OnBoard', '0154_remove_basedatatable_contract_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='upgrade_device_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wireless_number', models.CharField(max_length=15)),
                ('make', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('os', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('storage', models.CharField(blank=True, max_length=255, null=True)),
                ('imei_number', models.CharField(blank=True, max_length=255, null=True)),
                ('device_etf', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_device', models.CharField(blank=True, max_length=255, null=True)),
                ('mifi', models.CharField(blank=True, max_length=255, null=True)),
                ('smartphone', models.CharField(blank=True, max_length=255, null=True)),
                ('tablet', models.CharField(blank=True, max_length=255, null=True)),
                ('wearables', models.CharField(blank=True, max_length=255, null=True)),
                ('device_type', models.CharField(blank=True, max_length=255, null=True)),
                ('new_upgrade_date', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_device_by_user', to=settings.AUTH_USER_MODEL)),
                ('sub_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_company_upgrade_request', to='OnBoard.organizations')),
            ],
            options={
                'db_table': 'upgrade_device_request',
            },
        ),
    ]
