# Generated by Django 5.1.4 on 2025-09-23 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0080_upgrade_device_request'),
        ('OnBoard', '0154_remove_basedatatable_contract_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botchats',
            name='billChat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_chats', to='OnBoard.basedatatable'),
        ),
    ]
