# Generated by Django 5.1.4 on 2025-09-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0081_alter_botchats_billchat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upgrade_device_request',
            old_name='make',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='upgrade_device_request',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
