# Generated by Django 5.1.4 on 2025-09-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0082_rename_make_upgrade_device_request_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botchats',
            name='recommended_questions',
            field=models.JSONField(default=[]),
        ),
    ]
