# Generated by Django 5.1.4 on 2025-09-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0083_botchats_recommended_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botchats',
            name='recommended_questions',
            field=models.JSONField(default=list),
        ),
    ]
