# Generated by Django 5.1.4 on 2025-09-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0084_alter_botchats_recommended_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade_device_request',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
