# Generated by Django 5.1.4 on 2025-10-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0085_upgrade_device_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='botchats',
            name='is_df_empty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botchats',
            name='is_query_generated',
            field=models.BooleanField(default=False),
        ),
    ]
