# Generated by Django 5.1.4 on 2025-10-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0086_botchats_is_df_empty_botchats_is_query_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botchats',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
