# Generated by Django 5.1.4 on 2025-10-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0087_alter_botchats_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='botchats',
            name='is_query_answered',
            field=models.BooleanField(default=False),
        ),
    ]
