# Generated by Django 5.1.4 on 2025-10-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0088_botchats_is_query_answered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botchats',
            old_name='is_query_answered',
            new_name='is_query_ran',
        ),
    ]
