# Generated by Django 5.1.4 on 2025-10-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0089_rename_is_query_answered_botchats_is_query_ran'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenters',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
