# Generated by Django 5.1.4 on 2025-10-23 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0090_costcenters_remark'),
        ('OnBoard', '0159_remove_wirelesshistory_banonboarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroles',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_roles', to='OnBoard.company'),
        ),
        migrations.AddField(
            model_name='userroles',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_roles', to='OnBoard.organizations'),
        ),
    ]
