# Generated by Django 5.1.4 on 2025-10-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0091_userroles_company_userroles_organization'),
        ('OnBoard', '0159_remove_wirelesshistory_banonboarded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroles',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='userroles',
            constraint=models.UniqueConstraint(fields=('company', 'organization', 'name'), name='unique_role'),
        ),
    ]
