# Generated by Django 5.1.4 on 2025-11-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0092_alter_userroles_name_userroles_unique_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='authority_status',
            field=models.CharField(default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='upgrade_device_request',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
