# Generated by Django 5.1.4 on 2025-11-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0093_requests_authority_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade_device_request',
            name='authority_status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
