# Generated by Django 5.1.4 on 2025-11-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0094_upgrade_device_request_authority_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade_device_request',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
