# Generated by Django 5.1.4 on 2025-11-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0095_upgrade_device_request_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='makemodel',
            name='other_specifications',
            field=models.JSONField(default=dict),
        ),
    ]
