# Generated by Django 5.1.4 on 2025-11-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0096_makemodel_other_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='makemodel',
            name='accessory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
