# Generated by Django 5.1.4 on 2025-11-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0097_makemodel_accessory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Smartphone', 'Smartphone'), ('Accessory', 'Accessory')], max_length=255),
        ),
    ]
