# Generated by Django 5.1.4 on 2025-11-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0098_alter_device_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Smartphone', 'Smartphone'), ('Accessories', 'Accessories')], max_length=255),
        ),
    ]
