# Generated by Django 5.1.4 on 2025-11-24 06:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0099_alter_device_device_type'),
        ('OnBoard', '0164_uniquepdfdatatable_accessories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriesRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('Order', 'Order'), ('Replace', 'Replace'), ('Return', 'Return')], max_length=255)),
                ('request_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('ban', models.CharField(default='', max_length=255)),
                ('accessory_type', models.CharField(default='', max_length=255)),
                ('manufacturer', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('other_specifications', models.JSONField(default=dict)),
                ('cost_center', models.CharField(blank=True, max_length=255, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_code', models.CharField(blank=True, max_length=255, null=True)),
                ('location_type', models.CharField(blank=True, max_length=255, null=True)),
                ('o_address1', models.CharField(blank=True, max_length=255, null=True)),
                ('o_address2', models.CharField(blank=True, max_length=255, null=True)),
                ('o_city', models.CharField(blank=True, max_length=255, null=True)),
                ('o_state', models.CharField(blank=True, max_length=255, null=True)),
                ('o_zipcode', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_reuqest_organizations', to='OnBoard.organizations')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_reuqest_users', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_reuqest_vendors', to='Dashboard.vendors')),
            ],
            options={
                'db_table': 'AccessoriesRequest',
            },
        ),
    ]
