# Generated by Django 5.1.4 on 2025-11-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0100_accessoriesrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriesrequest',
            name='area_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesrequest',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesrequest',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesrequest',
            name='user_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
