# Generated by Django 5.1.4 on 2025-11-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0102_accessoriesrequest_authority_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriesrequest',
            name='line_of_service',
            field=models.CharField(default='123-456-7890', max_length=15),
        ),
    ]
