# Generated by Django 5.1.4 on 2025-11-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0103_accessoriesrequest_line_of_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriesrequest',
            name='p_address1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesrequest',
            name='p_address2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesrequest',
            name='p_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesrequest',
            name='p_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesrequest',
            name='p_zipcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
