# Generated by Django 5.1.4 on 2025-11-24 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0104_accessoriesrequest_p_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriesrequest',
            name='shipping_method',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
