# Generated by Django 5.1.4 on 2025-11-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0105_accessoriesrequest_shipping_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoriesrequest',
            name='shipping_method',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
