# Generated by Django 5.1.4 on 2025-11-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0106_alter_accessoriesrequest_shipping_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriesrequest',
            name='rl_address1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesrequest',
            name='rl_address2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesrequest',
            name='rl_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesrequest',
            name='rl_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesrequest',
            name='rl_zipcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
