# Generated by Django 5.1.4 on 2025-11-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0107_accessoriesrequest_rl_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriesrequest',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesrequest',
            name='estimated_delivery_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesrequest',
            name='receipt_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesrequest',
            name='shipping_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesrequest',
            name='shipping_vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesrequest',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
