# Generated by Django 5.1.4 on 2025-11-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0108_accessoriesrequest_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriesrequest',
            name='replacement_delivery_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesrequest',
            name='replacement_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesrequest',
            name='replacement_tracking_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesrequest',
            name='return_received_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesrequest',
            name='return_shipped_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesrequest',
            name='return_tracking_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
