# Generated by Django 5.1.4 on 2025-11-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0109_accessoriesrequest_replacement_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriesrequest',
            name='return_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
