# Generated by Django 5.1.4 on 2025-12-04 10:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0110_accessoriesrequest_return_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade_device_request',
            name='request_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='upgrade_device_request',
            name='request_type',
            field=models.CharField(default='upgrade_device_request', max_length=255),
        ),
    ]
