# Generated by Django 5.1.4 on 2025-12-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0111_upgrade_device_request_request_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriesrequest',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='upgrade_device_request',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
