# Generated by Django 5.1.4 on 2025-12-04 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0112_accessoriesrequest_user_name_and_more'),
        ('OnBoard', '0166_alter_mappingobjectban_monthly_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade_device_request',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_reuqest_organizations', to='OnBoard.organizations'),
        ),
    ]
