# Generated by Django 5.1.4 on 2025-12-04 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0113_upgrade_device_request_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade_device_request',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_reuqest_vendors', to='Dashboard.vendors'),
        ),
    ]
