# Generated by Django 5.1.4 on 2025-12-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0114_upgrade_device_request_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriesrequest',
            name='client_admin_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesrequest',
            name='employee_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessoriesrequest',
            name='portal_admin_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='client_admin_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='employee_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='portal_admin_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upgrade_device_request',
            name='client_admin_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upgrade_device_request',
            name='employee_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upgrade_device_request',
            name='portal_admin_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
