# Generated by Django 5.1.4 on 2025-12-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0115_accessoriesrequest_client_admin_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgrade_device_request',
            name='new_upgrade_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
