# Generated by Django 5.1.4 on 2026-01-07 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0116_alter_upgrade_device_request_new_upgrade_date'),
        ('OnBoard', '0173_alter_mappingobjectban_user_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='baselinecategories',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='baselinecategories',
            name='banObj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OnBoard.basedatatable'),
        ),
        migrations.AlterUniqueTogether(
            name='baselinecategories',
            unique_together={('organization', 'vendor', 'banObj', 'category')},
        ),
    ]
