# Generated by Django 5.1.4 on 2026-01-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0117_alter_baselinecategories_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makemodel',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='makemodel',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='makemodel',
            name='storage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
