# Generated by Django 5.1.4 on 2025-03-05 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dashboard', '0005_billtype'),
        ('OnBoard', '0065_contract_contract_file_contract_contract_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewUploadBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='ViewUploadedBills/')),
                ('month', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='company_view_upload_bills', to='OnBoard.company')),
                ('organization', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='organization_view_upload_bills', to='OnBoard.organizations')),
                ('vendor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_view_upload_bills', to='Dashboard.vendors')),
            ],
            options={
                'db_table': 'ViewUploadBill',
            },
        ),
    ]
