# Generated by Django 5.1.4 on 2025-03-05 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0065_contract_contract_file_contract_contract_name_and_more'),
        ('View', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewuploadbill',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_view_upload_bills', to='OnBoard.company'),
        ),
    ]
