# Generated by Django 5.1.4 on 2025-03-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0002_alter_viewuploadbill_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedWorkbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255)),
                ('vendor_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('workbook_name', models.CharField(max_length=255)),
                ('workbook_data', models.BinaryField()),
                ('bill_date_info', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ProcessedWorkbook',
            },
        ),
    ]
