# Generated by Django 5.1.4 on 2025-03-06 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0003_processedworkbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedworkbook',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='ViewUploadedBills/'),
        ),
        migrations.AddField(
            model_name='processedworkbook',
            name='uploadbill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_work', to='View.viewuploadbill'),
        ),
        migrations.AddField(
            model_name='viewuploadbill',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='ViewUploadedBills/'),
        ),
    ]
