# Generated by Django 5.1.4 on 2025-03-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0004_processedworkbook_output_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewuploadbill',
            name='types',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
