# Generated by Django 5.1.4 on 2025-03-07 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_billtype'),
        ('OnBoard', '0066_mappingobjectban_viewupload'),
        ('View', '0005_viewuploadbill_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='viewPaperBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255)),
                ('wireless_number', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(max_length=255)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_date', models.CharField(blank=True, max_length=255, null=True)),
                ('due_date', models.CharField(blank=True, max_length=255, null=True)),
                ('monthly_bill', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_view_paper_bills', to='OnBoard.company')),
                ('organization', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='organization_view_paper_bills', to='OnBoard.organizations')),
                ('vendor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_view_paper_bills', to='Dashboard.vendors')),
            ],
            options={
                'db_table': 'ViewPaperBill',
            },
        ),
    ]
