# Generated by Django 5.1.4 on 2025-03-25 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0083_delete_contract'),
        ('View', '0006_viewpaperbill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(blank=True, max_length=255, null=True)),
                ('term', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_file', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('basebans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_ban_contracts', to='OnBoard.basedatatable')),
                ('uploadedbans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_ban_contracts', to='OnBoard.uploadban')),
            ],
            options={
                'db_table': 'Contracts',
            },
        ),
    ]
