# Generated by Django 5.1.4 on 2025-03-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0007_contracts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contracts',
            old_name='basebans',
            new_name='baseban',
        ),
        migrations.RenameField(
            model_name='contracts',
            old_name='uploadedbans',
            new_name='uploadedban',
        ),
    ]
