# Generated by Django 5.1.4 on 2025-03-26 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0083_delete_contract'),
        ('View', '0008_rename_basebans_contracts_baseban_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='baseban',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_ban_contracts', to='OnBoard.basedatatable'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='uploadedban',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_ban_contracts', to='OnBoard.uploadban'),
        ),
    ]
