# Generated by Django 5.1.4 on 2025-03-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0009_alter_contracts_baseban_alter_contracts_uploadedban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='BanContracts/'),
        ),
    ]
