# Generated by Django 5.1.4 on 2025-06-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0015_alter_paperbill_bill_date_alter_paperbill_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='sub_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
