# Generated by Django 5.1.4 on 2025-06-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0016_contracts_sub_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='status',
            field=models.CharField(blank=True, default='Active', max_length=255, null=True),
        ),
    ]
