# Generated by Django 5.1.4 on 2025-08-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0017_alter_contracts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewuploadbill',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
