# Generated by Django 5.1.4 on 2025-09-18 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0153_onboardban_contract_file_onboardban_contract_name'),
        ('View', '0018_viewuploadbill_is_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='baseban',
        ),
        migrations.AddField(
            model_name='contracts',
            name='onboardedban',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarded_ban_contracts', to='OnBoard.onboardban'),
        ),
    ]
