# Generated by Django 5.1.4 on 2025-09-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0019_remove_contracts_baseban_contracts_onboardedban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='contract_file',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
