# Generated by Django 5.1.4 on 2025-09-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0020_alter_contracts_contract_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='ban-contracts/'),
        ),
    ]
