# Generated by Django 5.1.4 on 2025-10-15 12:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0021_alter_contracts_contract_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillAnalysisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_date', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_day', models.IntegerField(default=0)),
                ('bill_month', models.IntegerField(default=0)),
                ('bill_year', models.IntegerField(default=0)),
                ('data_usage_range', models.CharField(choices=[('zero_usage', 'Zero Usage'), ('less_than_5_gb', 'Less than 5 GB'), ('between_5_and_15_gb', 'Between 5 and 15 GB'), ('more_than_15_gb', 'More than 15 GB'), ('NA_not_unlimited', 'N/A (Not Unlimited)'), ('NA_unlimited', 'N/A (Unlimited)')], max_length=50)),
                ('wireless_number', models.CharField(max_length=20)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('current_plan', models.CharField(blank=True, max_length=255, null=True)),
                ('current_plan_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_plan_usage', models.CharField(default='NA', max_length=10)),
                ('is_plan_recommended', models.BooleanField(default=False)),
                ('recommended_plan', models.CharField(blank=True, max_length=255, null=True)),
                ('recommended_plan_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recommended_plan_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('variance_with_last_month', models.CharField(default='NA', max_length=10)),
                ('how_variance_is_related_with_last_month', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_analysis_data', to='View.viewuploadbill')),
            ],
            options={
                'db_table': 'BillAnalysisData',
            },
        ),
        migrations.CreateModel(
            name='BillSummaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(help_text='Unique identifier for the customer account', max_length=255)),
                ('bill_date', models.CharField(help_text='Date of the billing cycle (e.g., 2024-09-01)', max_length=255)),
                ('bill_day', models.IntegerField(default=0)),
                ('bill_month', models.IntegerField(default=0)),
                ('bill_year', models.IntegerField(default=0)),
                ('wireless_number', models.CharField(help_text='10-digit wireless/phone number', max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_number', message='Wireless number must be exactly 10 digits', regex='^\\d{10}$')])),
                ('username', models.CharField(blank=True, help_text='Name of the user associated with the wireless number', max_length=255, null=True)),
                ('data_roaming', models.CharField(default='NA', help_text='Data roaming charges for the billing cycle', max_length=255)),
                ('message_roaming', models.CharField(default='NA', help_text='SMS/MMS roaming charges for the billing cycle', max_length=255)),
                ('voice_roaming', models.CharField(default='NA', help_text='Voice call roaming charges for the billing cycle', max_length=255)),
                ('data_usage', models.CharField(default='NA', help_text='Total data usage (in GB) during the billing cycle', max_length=255)),
                ('message_usage', models.CharField(default='NA', help_text='Total number of SMS/MMS messages sent during the billing cycle', max_length=255)),
                ('voice_plan_usage', models.CharField(default='NA', help_text='Total voice minutes used during the billing cycle', max_length=255)),
                ('total_charges', models.CharField(default='NA', help_text='Grand total charges on the bill', max_length=255)),
                ('third_party_charges', models.CharField(default='NA', help_text='Third-party charges including tax', max_length=255)),
                ('taxes_governmental_surcharges', models.CharField(default='NA', help_text='Taxes and government surcharges applied to the bill', max_length=255)),
                ('other_charges_credits', models.CharField(default='NA', help_text='Other charges or credits applied (e.g., discounts, adjustments)', max_length=255)),
                ('equipment_charges', models.CharField(default='NA', help_text='Charges for equipment or device installments', max_length=255)),
                ('usage_purchase_charges', models.CharField(default='NA', help_text='Charges for extra usage or purchases beyond the plan', max_length=255)),
                ('plan', models.CharField(default='NA', help_text='Name of the subscribed wireless plan', max_length=255)),
                ('monthly_charges', models.CharField(default='NA', help_text='Base monthly plan charges', max_length=255)),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_summary', to='View.viewuploadbill')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('wireless_number', 'bill_date', 'bill_id'), name='bill_unique_wireless_number_bill_date_id')],
            },
        ),
    ]
