# Generated by Django 5.1.4 on 2025-10-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0022_billanalysisdata_billsummarydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='billanalysisdata',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billanalysisdata',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billsummarydata',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billsummarydata',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
