# Generated by Django 5.1.4 on 2025-10-15 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View', '0023_billanalysisdata_company_billanalysisdata_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billsummarydata',
            name='bill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_summary_data', to='View.viewuploadbill'),
        ),
    ]
