# Generated by Django 5.1.4 on 2025-12-02 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0164_uniquepdfdatatable_accessories'),
        ('View', '0024_alter_billsummarydata_bill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperbill',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_view_onboard_bills', to='OnBoard.organizations'),
        ),
    ]
