# Generated by Django 5.1.4 on 2025-06-09 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='comapany',
            new_name='company',
        ),
    ]
