# Generated by Django 5.1.4 on 2025-06-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0002_rename_comapany_ticket_company'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reminder',
            table='Reminder',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='Ticket',
        ),
    ]
