# Generated by Django 5.1.4 on 2025-10-11 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0157_basedatatable_billingcurrency'),
        ('Settings', '0003_alter_reminder_table_alter_ticket_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companyreminders', to='OnBoard.company'),
        ),
    ]
