# Generated by Django 5.1.4 on 2025-10-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0089_rename_is_query_answered_botchats_is_query_ran'),
        ('Settings', '0004_reminder_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='to_roles',
            field=models.ManyToManyField(blank=True, to='Dashboard.userroles'),
        ),
    ]
