# Generated by Django 5.1.4 on 2025-10-15 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0159_remove_wirelesshistory_banonboarded_and_more'),
        ('Settings', '0005_reminder_to_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=255)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('banOnboarded', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banOnboardedhistory', to='OnBoard.onboardban')),
                ('banUploaded', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banuploadedhistory', to='OnBoard.uploadban')),
            ],
            options={
                'db_table': 'BanHistory',
            },
        ),
        migrations.CreateModel(
            name='WirelessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wireless_number', models.CharField(max_length=255)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('banOnboarded', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wirelessOnboardedhistory', to='OnBoard.onboardban')),
                ('banUploaded', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wirelessuploadedhistory', to='OnBoard.uploadban')),
            ],
            options={
                'db_table': 'WirelessHistory',
            },
        ),
    ]
