# Generated by Django 5.1.4 on 2025-10-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0006_banhistory_wirelesshistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banhistory',
            name='action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
