# Generated by Django 5.1.4 on 2025-10-20 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0090_costcenters_remark'),
        ('OnBoard', '0159_remove_wirelesshistory_banonboarded_and_more'),
        ('Settings', '0007_alter_banhistory_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionsbyCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_permissions', to='OnBoard.company')),
                ('permssion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_by_company', to='Dashboard.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='Dashboard.userroles')),
            ],
            options={
                'db_table': 'PermissionsbyCompany',
            },
        ),
    ]
