# Generated by Django 5.1.4 on 2025-10-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0008_permissionsbycompany'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PermissionsbyCompany',
        ),
    ]
