# Generated by Django 5.1.4 on 2025-10-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0090_costcenters_remark'),
        ('Settings', '0010_permissionsbycompany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionsbycompany',
            name='permssion',
        ),
        migrations.AddField(
            model_name='permissionsbycompany',
            name='permssion',
            field=models.ManyToManyField(related_name='permissions_by_company', to='Dashboard.permission'),
        ),
    ]
