# Generated by Django 5.1.4 on 2025-10-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0011_remove_permissionsbycompany_permssion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissionsbycompany',
            old_name='permssion',
            new_name='permissions',
        ),
    ]
