# Generated by Django 5.1.4 on 2025-10-20 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0090_costcenters_remark'),
        ('Settings', '0013_alter_permissionsbycompany_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionsbycompany',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='Dashboard.userroles'),
        ),
    ]
