# Generated by Django 5.1.4 on 2025-10-23 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0159_remove_wirelesshistory_banonboarded_and_more'),
        ('Settings', '0014_alter_permissionsbycompany_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionsbycompany',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_permissions', to='OnBoard.organizations'),
        ),
    ]
