# Generated by Django 5.1.4 on 2025-10-23 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0159_remove_wirelesshistory_banonboarded_and_more'),
        ('Settings', '0015_permissionsbycompany_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionsbycompany',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_permissions', to='OnBoard.company'),
        ),
    ]
