# Generated by Django 5.1.4 on 2025-11-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0092_alter_userroles_name_userroles_unique_role'),
        ('Settings', '0016_alter_permissionsbycompany_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionsbycompany',
            name='role',
        ),
        migrations.AddField(
            model_name='permissionsbycompany',
            name='role',
            field=models.ManyToManyField(related_name='role_permissions', to='Dashboard.userroles'),
        ),
    ]
