# Generated by Django 5.1.4 on 2025-11-05 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0092_alter_userroles_name_userroles_unique_role'),
        ('Settings', '0017_remove_permissionsbycompany_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionsbycompany',
            name='role',
        ),
        migrations.AddField(
            model_name='permissionsbycompany',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='Dashboard.userroles'),
        ),
    ]
