# Generated by Django 5.1.4 on 2025-11-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0018_remove_permissionsbycompany_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wirelesshistory',
            name='action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
