# Generated by Django 5.1.4 on 2025-02-20 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dashboard', '0005_billtype'),
        ('OnBoard', '0041_uniquepdfdatatable_cost_centers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('remark', models.TextField(blank=True, max_length=255, null=True)),
                ('uploadBill', models.FileField(upload_to='BillAnalysis/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='companyanalysis', to='OnBoard.company')),
                ('vendor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vendoranalysis', to='Dashboard.vendors')),
            ],
            options={
                'db_table': 'Analysis',
            },
        ),
    ]
