# Generated by Django 5.1.4 on 2025-02-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0002_analysis_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='excel',
            field=models.FileField(blank=True, null=True, upload_to='BillAnalysis/'),
        ),
    ]
