# Generated by Django 5.1.4 on 2025-02-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0003_analysis_excel'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='bill_date_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
