# Generated by Django 5.1.4 on 2025-04-03 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0004_analysis_bill_date_info'),
        ('OnBoard', '0086_baselinedatatable_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companyanalysis', to='OnBoard.company'),
        ),
    ]
