# Generated by Django 5.1.4 on 2025-09-18 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0006_analysis_is_processed'),
        ('Dashboard', '0075_botchats'),
        ('OnBoard', '0152_alter_organizations_domain_alter_organizations_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('remark', models.TextField(blank=True, max_length=255, null=True)),
                ('file1', models.FileField(upload_to='MultipleFileUpload/')),
                ('file2', models.FileField(upload_to='MultipleFileUpload/')),
                ('file3', models.FileField(upload_to='MultipleFileUpload/')),
                ('excel', models.FileField(blank=True, null=True, upload_to='BillAnalysis/')),
                ('is_processed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companyanalysismultiple', to='OnBoard.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multipleanalysisby', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vendoranalysismultiple', to='Dashboard.vendors')),
            ],
            options={
                'db_table': 'MultipleFileUpload',
            },
        ),
        migrations.CreateModel(
            name='AnalysisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_date', models.CharField(blank=True, max_length=255, null=True)),
                ('data_type', models.CharField(choices=[('zero_usage', 'Zero Usage'), ('less_than_5_gb', 'Less than 5 GB'), ('between_5_and_15_gb', 'Between 5 and 15 GB'), ('more_than_15_gb', 'More than 15 GB'), ('NA_not_unlimited', 'N/A (Not Unlimited)'), ('NA_unlimited', 'N/A (Unlimited)')], max_length=50)),
                ('wireless_number', models.CharField(max_length=20)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('current_plan', models.CharField(blank=True, max_length=255, null=True)),
                ('current_plan_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_plan_usage', models.CharField(default='NA', max_length=10)),
                ('recommended_plan', models.CharField(blank=True, max_length=255, null=True)),
                ('recommended_plan_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recommended_plan_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysisdata', to='Analysis.analysis')),
                ('multiple_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multipleanalysis', to='Analysis.multiplefileupload')),
            ],
            options={
                'db_table': 'AnalysisData',
            },
        ),
    ]
