# Generated by Django 5.1.4 on 2025-09-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0007_multiplefileupload_analysisdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisdata',
            name='multiple_analysis',
        ),
        migrations.DeleteModel(
            name='MultipleFileUpload',
        ),
    ]
