# Generated by Django 5.1.4 on 2025-09-18 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0008_remove_analysisdata_multiple_analysis_and_more'),
        ('Dashboard', '0075_botchats'),
        ('OnBoard', '0152_alter_organizations_domain_alter_organizations_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('remark', models.TextField(blank=True, max_length=255, null=True)),
                ('file1', models.FileField(upload_to='MultipleFileUpload/')),
                ('file2', models.FileField(upload_to='MultipleFileUpload/')),
                ('file3', models.FileField(upload_to='MultipleFileUpload/')),
                ('excel', models.FileField(blank=True, null=True, upload_to='BillAnalysis/')),
                ('is_processed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companyanalysismultiple', to='OnBoard.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multipleanalysisby', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vendoranalysismultiple', to='Dashboard.vendors')),
            ],
            options={
                'db_table': 'MultipleFileUpload',
            },
        ),
    ]
