# Generated by Django 5.1.4 on 2025-09-18 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0009_multiplefileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisdata',
            name='multiple_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multipleanalysis', to='Analysis.multiplefileupload'),
        ),
    ]
