# Generated by Django 5.1.4 on 2025-09-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0010_analysisdata_multiple_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplefileupload',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='MultipleFileUpload/'),
        ),
        migrations.AlterField(
            model_name='multiplefileupload',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='MultipleFileUpload/'),
        ),
        migrations.AlterField(
            model_name='multiplefileupload',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='MultipleFileUpload/'),
        ),
    ]
