# Generated by Django 5.1.4 on 2025-09-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0012_summarydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarydata',
            name='third_party_charges',
            field=models.CharField(default='NA', help_text='Third-party charges including tax', max_length=255),
        ),
    ]
