# Generated by Django 5.1.4 on 2025-09-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0013_summarydata_third_party_charges'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='summarydata',
            constraint=models.UniqueConstraint(fields=('wireless_number', 'bill_date'), name='unique_wireless_number_bill_date'),
        ),
        migrations.AlterModelTable(
            name='summarydata',
            table=None,
        ),
    ]
