# Generated by Django 5.1.4 on 2025-09-22 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0014_summarydata_unique_wireless_number_bill_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SummaryData',
        ),
    ]
