# Generated by Django 5.1.4 on 2025-09-22 07:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0015_delete_summarydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(help_text='Unique identifier for the customer account', max_length=255)),
                ('bill_date', models.CharField(help_text='Date of the billing cycle (e.g., 2024-09-01)', max_length=255)),
                ('wireless_number', models.CharField(help_text='10-digit wireless/phone number', max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_number', message='Wireless number must be exactly 10 digits', regex='^\\d{10}$')])),
                ('username', models.CharField(blank=True, help_text='Name of the user associated with the wireless number', max_length=255, null=True)),
                ('data_roaming', models.CharField(default='NA', help_text='Data roaming charges for the billing cycle', max_length=255)),
                ('message_roaming', models.CharField(default='NA', help_text='SMS/MMS roaming charges for the billing cycle', max_length=255)),
                ('voice_roaming', models.CharField(default='NA', help_text='Voice call roaming charges for the billing cycle', max_length=255)),
                ('data_usage', models.CharField(default='NA', help_text='Total data usage (in GB) during the billing cycle', max_length=255)),
                ('message_usage', models.CharField(default='NA', help_text='Total number of SMS/MMS messages sent during the billing cycle', max_length=255)),
                ('voice_plan_usage', models.CharField(default='NA', help_text='Total voice minutes used during the billing cycle', max_length=255)),
                ('total_charges', models.CharField(default='NA', help_text='Grand total charges on the bill', max_length=255)),
                ('third_party_charges', models.CharField(default='NA', help_text='Third-party charges including tax', max_length=255)),
                ('taxes_governmental_surcharges', models.CharField(default='NA', help_text='Taxes and government surcharges applied to the bill', max_length=255)),
                ('other_charges_credits', models.CharField(default='NA', help_text='Other charges or credits applied (e.g., discounts, adjustments)', max_length=255)),
                ('equipment_charges', models.CharField(default='NA', help_text='Charges for equipment or device installments', max_length=255)),
                ('usage_purchase_charges', models.CharField(default='NA', help_text='Charges for extra usage or purchases beyond the plan', max_length=255)),
                ('plan', models.CharField(default='NA', help_text='Name of the subscribed wireless plan', max_length=255)),
                ('monthly_charges', models.CharField(default='NA', help_text='Base monthly plan charges', max_length=255)),
                ('multiple_analysis', models.ForeignKey(blank=True, help_text='Reference to the uploaded file set for this analysis', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_data', to='Analysis.multiplefileupload')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('wireless_number', 'bill_date'), name='unique_wireless_number_bill_date')],
            },
        ),
    ]
