# Generated by Django 5.1.4 on 2025-09-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0016_summarydata'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='summarydata',
            name='unique_wireless_number_bill_date',
        ),
        migrations.AddConstraint(
            model_name='summarydata',
            constraint=models.UniqueConstraint(fields=('wireless_number', 'bill_date', 'multiple_analysis'), name='unique_wireless_number_bill_date'),
        ),
    ]
