# Generated by Django 5.1.4 on 2025-09-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0018_remove_summarydata_unique_wireless_number_bill_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisdata',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='summarydata',
            name='file1_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
