# Generated by Django 5.1.4 on 2025-09-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0019_analysisdata_file_name_summarydata_file1_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summarydata',
            old_name='file1_name',
            new_name='file_name',
        ),
    ]
