# Generated by Django 5.1.4 on 2025-09-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0020_rename_file1_name_summarydata_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisdata',
            name='bill_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisdata',
            name='bill_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisdata',
            name='bill_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summarydata',
            name='bill_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summarydata',
            name='bill_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summarydata',
            name='bill_year',
            field=models.IntegerField(default=0),
        ),
    ]
