# Generated by Django 5.1.4 on 2025-09-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0021_analysisdata_bill_day_analysisdata_bill_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'APIKey',
            },
        ),
    ]
