# Generated by Django 5.1.4 on 2025-09-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0022_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisdata',
            name='is_plan_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
