# Generated by Django 5.1.4 on 2025-10-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0023_analysisdata_is_plan_recommended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisdata',
            old_name='data_type',
            new_name='data_usage_range',
        ),
    ]
