# Generated by Django 5.1.4 on 2025-10-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0024_rename_data_type_analysisdata_data_usage_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisdata',
            name='how_variance_is_related_with_last_month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='analysisdata',
            name='variance_with_last_month',
            field=models.FloatField(default=0),
        ),
    ]
