# Generated by Django 5.1.4 on 2025-10-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0025_analysisdata_how_variance_is_related_with_last_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisdata',
            name='variance_with_last_month',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
