# Generated by Django 5.1.4 on 2025-10-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0026_alter_analysisdata_variance_with_last_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisdata',
            name='savings_pdf',
            field=models.FileField(blank=True, null=True, upload_to='SavingsPDF/'),
        ),
    ]
