# Generated by Django 5.1.4 on 2025-10-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0027_analysisdata_savings_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisdata',
            name='savings_pdf',
        ),
        migrations.AddField(
            model_name='multiplefileupload',
            name='savings_pdf',
            field=models.FileField(blank=True, null=True, upload_to='SavingsPDF/'),
        ),
    ]
