# Generated by Django 5.1.4 on 2025-10-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0028_remove_analysisdata_savings_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisdata',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysisdata',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='summarydata',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='summarydata',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
