# Generated by Django 5.1.4 on 2025-10-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0029_analysisdata_company_analysisdata_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisdata',
            name='company',
        ),
        migrations.RemoveField(
            model_name='analysisdata',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='summarydata',
            name='company',
        ),
        migrations.RemoveField(
            model_name='summarydata',
            name='vendor',
        ),
    ]
