# Generated by Django 5.1.4 on 2025-02-11 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0021_rename_plantype_mappingobjectban_plan_type'),
        ('authenticate', '0002_userlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companyusers', to='OnBoard.company', verbose_name='Company'),
        ),
    ]
