# Generated by Django 5.1.4 on 2025-03-13 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_billtype'),
        ('OnBoard', '0067_batchreport_output_file_alter_batchreport_table'),
        ('authenticate', '0003_portaluser_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companyusers', to='OnBoard.company'),
        ),
        migrations.AlterField(
            model_name='portaluser',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='Dashboard.userroles'),
        ),
    ]
