# Generated by Django 5.1.4 on 2025-03-13 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_billtype'),
        ('authenticate', '0004_alter_portaluser_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designation', to='Dashboard.userroles'),
        ),
    ]
