# Generated by Django 5.1.4 on 2025-04-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_portaluser_mobile_number_portaluser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='contact_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
