# Generated by Django 5.1.4 on 2025-09-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='string_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
