# Generated by Django 5.1.4 on 2025-09-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0009_portaluser_string_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
