# Generated by Django 5.1.4 on 2025-10-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0010_portaluser_account_number_portaluser_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='temp_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
