# Generated by Django 5.1.4 on 2025-10-22 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0090_costcenters_remark'),
        ('OnBoard', '0159_remove_wirelesshistory_banonboarded_and_more'),
        ('authenticate', '0011_portaluser_temp_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_users', to='OnBoard.organizations'),
        ),
        migrations.AlterField(
            model_name='portaluser',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_users', to='Dashboard.vendors'),
        ),
    ]
