# Generated by Django 5.1.4 on 2025-11-06 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0160_basedatatable_uploaded_by'),
        ('authenticate', '0012_alter_portaluser_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogs',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OnBoard.organizations'),
        ),
    ]
