# Generated by Django 5.1.4 on 2025-11-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0013_userlogs_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogs',
            name='description',
            field=models.TextField(db_index=True),
        ),
    ]
