# Generated by Django 5.1.4 on 2026-01-05 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0014_alter_userlogs_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WirelessNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wireless_numbers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'WirelessNumber',
            },
        ),
    ]
