# Generated by Django 5.1.4 on 2026-01-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0015_wirelessnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
