# Generated by Django 5.1.4 on 2026-01-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0016_alter_portaluser_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WirelessNumber',
            new_name='EmployeeWirelessNumber',
        ),
    ]
