# Generated by Django 5.1.4 on 2026-01-05 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0017_rename_wirelessnumber_employeewirelessnumber'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeewirelessnumber',
            table='EmployeeWirelessNumber',
        ),
    ]
