# Generated by Django 5.1.4 on 2026-01-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0019_portaluser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
