# Generated by Django 5.1.4 on 2025-02-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='status',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
