# Generated by Django 5.1.4 on 2025-02-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0003_location_company_alter_location_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='bulk_upload_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='bulk_upload_location'),
        ),
    ]
