# Generated by Django 5.1.4 on 2025-02-06 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0004_location_bulk_upload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk_upload_file', models.FileField(blank=True, default=None, null=True, upload_to='bulk_upload_location')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'BulkLocation',
            },
        ),
        migrations.RemoveField(
            model_name='location',
            name='bulk_upload_file',
        ),
        migrations.AddField(
            model_name='location',
            name='bulkfile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_uploads', to='OnBoard.bulklocation'),
        ),
    ]
