# Generated by Django 5.1.4 on 2025-02-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0005_bulklocation_remove_location_bulk_upload_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulklocation',
            old_name='bulk_upload_file',
            new_name='file',
        ),
    ]
