# Generated by Django 5.1.4 on 2025-02-06 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0006_rename_bulk_upload_file_bulklocation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulklocation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk', to='OnBoard.organizations'),
        ),
    ]
