# Generated by Django 5.1.4 on 2025-02-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0007_bulklocation_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='end_user_admin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizations',
            name='end_user_billing',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizations',
            name='end_users',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizations',
            name='other_domains',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
