# Generated by Django 5.1.4 on 2025-02-07 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_billtype'),
        ('OnBoard', '0008_organizations_end_user_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_it_consolidatedBan', models.BooleanField(default=False)),
                ('addDataToBaseline', models.BooleanField(default=False)),
                ('uploadBill', models.FileField(upload_to='BanUploadBill/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('entryType', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrytypeban', to='Dashboard.entrytype')),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locationOnboardBan', to='OnBoard.location')),
                ('masteraccount', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masteraccOnboardBan', to='Dashboard.entrytype')),
                ('organization', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboardban_organization', to='OnBoard.organizations')),
                ('vendor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboardban_vendors', to='Dashboard.vendors')),
            ],
            options={
                'db_table': 'OnboardBAN',
            },
        ),
        migrations.CreateModel(
            name='UploadBAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_it_consolidatedBan', models.BooleanField(default=False)),
                ('auto_pay_enabled', models.BooleanField(default=False)),
                ('vendor_alias', models.CharField(blank=True, max_length=255, null=True)),
                ('vendorCS', models.CharField(blank=True, max_length=255, null=True)),
                ('BillingCurrency', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(max_length=255, unique=True)),
                ('account_password', models.CharField(blank=True, max_length=255, null=True)),
                ('payor', models.CharField(blank=True, max_length=255, null=True)),
                ('GlCode', models.CharField(blank=True, max_length=255, null=True)),
                ('ContractTerms', models.CharField(blank=True, max_length=255, null=True)),
                ('ContractNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('Services', models.CharField(blank=True, max_length=255, null=True)),
                ('Billing_cycle', models.CharField(blank=True, max_length=255, null=True)),
                ('BillingDay', models.CharField(blank=True, max_length=255, null=True)),
                ('PayTerm', models.CharField(blank=True, max_length=255, null=True)),
                ('AccCharge', models.CharField(blank=True, max_length=255, null=True)),
                ('CustomerOfRecord', models.CharField(blank=True, max_length=255, null=True)),
                ('costcenterstatus', models.BooleanField(default=False)),
                ('CostCenter', models.CharField(blank=True, max_length=255, null=True)),
                ('CostCenterNotes', models.TextField(blank=True, null=True)),
                ('PO', models.CharField(blank=True, max_length=255, null=True)),
                ('Displaynotesonbillprocessing', models.BooleanField(default=False)),
                ('POamt', models.CharField(blank=True, max_length=255, null=True)),
                ('FoundAcc', models.CharField(blank=True, max_length=255, null=True)),
                ('BillingName', models.CharField(blank=True, max_length=255, null=True)),
                ('BillingAdd', models.CharField(blank=True, max_length=255, null=True)),
                ('BillingState', models.CharField(blank=True, max_length=255, null=True)),
                ('BillingZip', models.CharField(blank=True, max_length=255, null=True)),
                ('BillingCity', models.CharField(blank=True, max_length=255, null=True)),
                ('BillingCountry', models.CharField(blank=True, max_length=255, null=True)),
                ('BillingAtn', models.CharField(blank=True, max_length=255, null=True)),
                ('RemittanceName', models.CharField(blank=True, max_length=255, null=True)),
                ('RemittanceAdd', models.CharField(max_length=255)),
                ('RemittanceState', models.CharField(max_length=255)),
                ('RemittanceZip', models.CharField(max_length=255)),
                ('RemittanceCity', models.CharField(max_length=255)),
                ('RemittanceCountry', models.CharField(blank=True, max_length=255, null=True)),
                ('RemittanceAtn', models.CharField(blank=True, max_length=255, null=True)),
                ('RemittanceNotes', models.EmailField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('Vendor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='Dashboard.vendors')),
                ('banstatus', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banstatus', to='Dashboard.banstatus')),
                ('bantype', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bantype', to='Dashboard.bantype')),
                ('company', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='companyBAN', to='OnBoard.company')),
                ('costcenterlevel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costcenterlvlban', to='Dashboard.costcenterlevel')),
                ('costcentertype', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costcentertypban', to='Dashboard.costcentertype')),
                ('entryType', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrytype', to='Dashboard.entrytype')),
                ('invoicemethod', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoicemethod', to='Dashboard.invoicemethod')),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='OnBoard.location')),
                ('masteraccount', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masteraccUploadBan', to='Dashboard.entrytype')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='OnBoard.organizations')),
                ('paymenttype', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paytype', to='Dashboard.paymenttype')),
            ],
            options={
                'db_table': 'UploadBAN',
            },
        ),
        migrations.CreateModel(
            name='InventoryUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadFile', models.FileField(upload_to='InventoryExcel/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryupload_organizations', to='OnBoard.organizations')),
                ('vendor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventoryupload_vendors', to='Dashboard.vendors')),
                ('ban', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryupload_uploadBAN', to='OnBoard.uploadban')),
            ],
            options={
                'db_table': 'InventoryUpload',
            },
        ),
        migrations.AddConstraint(
            model_name='uploadban',
            constraint=models.UniqueConstraint(fields=('company', 'organization', 'account_number'), name='unique_ban'),
        ),
    ]
