# Generated by Django 5.1.4 on 2025-02-07 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_billtype'),
        ('OnBoard', '0009_onboardban_uploadban_inventoryupload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardban',
            name='billType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billtypes', to='Dashboard.billtype'),
        ),
        migrations.AlterField(
            model_name='inventoryupload',
            name='ban',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryupload_uploadBAN', to='OnBoard.uploadban'),
        ),
        migrations.AlterField(
            model_name='inventoryupload',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventoryupload_vendors', to='Dashboard.vendors'),
        ),
        migrations.AlterField(
            model_name='onboardban',
            name='entryType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrytypeban', to='Dashboard.entrytype'),
        ),
        migrations.AlterField(
            model_name='onboardban',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locationOnboardBan', to='OnBoard.location'),
        ),
        migrations.AlterField(
            model_name='onboardban',
            name='masteraccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masteraccOnboardBan', to='Dashboard.entrytype'),
        ),
        migrations.AlterField(
            model_name='onboardban',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboardban_organization', to='OnBoard.organizations'),
        ),
        migrations.AlterField(
            model_name='onboardban',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboardban_vendors', to='Dashboard.vendors'),
        ),
        migrations.AlterField(
            model_name='uploadban',
            name='Vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='Dashboard.vendors'),
        ),
        migrations.AlterField(
            model_name='uploadban',
            name='banstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banstatus', to='Dashboard.banstatus'),
        ),
        migrations.AlterField(
            model_name='uploadban',
            name='bantype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bantype', to='Dashboard.bantype'),
        ),
        migrations.AlterField(
            model_name='uploadban',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='companyBAN', to='OnBoard.company'),
        ),
        migrations.AlterField(
            model_name='uploadban',
            name='costcenterlevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costcenterlvlban', to='Dashboard.costcenterlevel'),
        ),
        migrations.AlterField(
            model_name='uploadban',
            name='costcentertype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costcentertypban', to='Dashboard.costcentertype'),
        ),
        migrations.AlterField(
            model_name='uploadban',
            name='entryType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrytype', to='Dashboard.entrytype'),
        ),
        migrations.AlterField(
            model_name='uploadban',
            name='invoicemethod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoicemethod', to='Dashboard.invoicemethod'),
        ),
        migrations.AlterField(
            model_name='uploadban',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='OnBoard.location'),
        ),
        migrations.AlterField(
            model_name='uploadban',
            name='masteraccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masteraccUploadBan', to='Dashboard.entrytype'),
        ),
        migrations.AlterField(
            model_name='uploadban',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='OnBoard.organizations'),
        ),
        migrations.AlterField(
            model_name='uploadban',
            name='paymenttype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paytype', to='Dashboard.paymenttype'),
        ),
    ]
