# Generated by Django 5.1.4 on 2025-02-08 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0010_onboardban_billtype_alter_inventoryupload_ban_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wireless_number', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('planType', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('vendor_number', models.CharField(max_length=255)),
                ('deviceid', models.CharField(blank=True, max_length=255, null=True)),
                ('mobiledevice', models.CharField(blank=True, max_length=255, null=True)),
                ('mobileIMEI', models.CharField(blank=True, max_length=255, null=True)),
                ('mobileSIMnumber', models.CharField(blank=True, max_length=255, null=True)),
                ('upgradeEligibleDate', models.CharField(blank=True, max_length=255, null=True)),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('voiceplanMins', models.CharField(blank=True, max_length=255, null=True)),
                ('voiceplanCharges', models.CharField(blank=True, max_length=255, null=True)),
                ('dataplanAllotment', models.CharField(blank=True, max_length=255, null=True)),
                ('dataplanCharges', models.CharField(blank=True, max_length=255, null=True)),
                ('mobileaccessCharges', models.CharField(blank=True, max_length=255, null=True)),
                ('thirdpartyappCharge', models.CharField(blank=True, max_length=255, null=True)),
                ('internationalvoiceFeat', models.CharField(blank=True, max_length=255, null=True)),
                ('internationaldataFeat', models.CharField(blank=True, max_length=255, null=True)),
                ('internationaltextFeat', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance', models.CharField(blank=True, max_length=255, null=True)),
                ('userstatus', models.CharField(blank=True, max_length=255, null=True)),
                ('useremail', models.CharField(blank=True, max_length=255, null=True)),
                ('devicetype', models.CharField(blank=True, max_length=255, null=True)),
                ('devicesmake', models.CharField(blank=True, max_length=255, null=True)),
                ('devicesmodel', models.CharField(blank=True, max_length=255, null=True)),
                ('devicescolor', models.CharField(blank=True, max_length=255, null=True)),
                ('devicesstorage', models.CharField(blank=True, max_length=255, null=True)),
                ('devicesOS', models.CharField(blank=True, max_length=255, null=True)),
                ('deviceSerialnumber', models.CharField(blank=True, max_length=255, null=True)),
                ('deviceETF', models.CharField(blank=True, max_length=255, null=True)),
                ('deviceAmount', models.CharField(blank=True, max_length=255, null=True)),
                ('deviceCredit', models.CharField(blank=True, max_length=255, null=True)),
                ('planName', models.CharField(blank=True, max_length=255, null=True)),
                ('planlineNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('location_address_1', models.CharField(blank=True, max_length=255, null=True)),
                ('location_address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('location_city', models.CharField(blank=True, max_length=255, null=True)),
                ('location_state', models.CharField(blank=True, max_length=255, null=True)),
                ('location_zip', models.CharField(blank=True, max_length=255, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=255, null=True)),
                ('cost_center_status', models.CharField(blank=True, max_length=255, null=True)),
                ('cost_center_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='OnBoard.uploadban')),
            ],
            options={
                'db_table': 'Lines',
                'unique_together': {('account_number', 'wireless_number')},
            },
        ),
    ]
