# Generated by Django 5.1.4 on 2025-02-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0012_uploadban_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadban',
            name='RemittanceNotes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
