# Generated by Django 5.1.4 on 2025-02-08 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_billtype'),
        ('OnBoard', '0013_alter_uploadban_remittancenotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadban',
            name='costcenterlevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costcenterlevel', to='Dashboard.costcenterlevel'),
        ),
        migrations.AlterField(
            model_name='uploadban',
            name='costcentertype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costcentertype', to='Dashboard.costcentertype'),
        ),
    ]
