# Generated by Django 5.1.4 on 2025-02-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_billtype'),
        ('OnBoard', '0014_alter_uploadban_costcenterlevel_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryupload',
            unique_together={('organization', 'vendor', 'ban')},
        ),
    ]
