# Generated by Django 5.1.4 on 2025-02-08 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0015_alter_inventoryupload_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardban',
            name='masteraccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masteraccOnboardBan', to='OnBoard.uploadban'),
        ),
        migrations.CreateModel(
            name='MappingObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='OnBoard.inventoryupload')),
            ],
            options={
                'db_table': 'MappingObject',
            },
        ),
    ]
