# Generated by Django 5.1.4 on 2025-02-08 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0016_alter_onboardban_masteraccount_mappingobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingobject',
            name='AccountNumber',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='CostCenters',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='DataPlanAllotment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='DataPlanCharges',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='DeviceAmount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='DeviceColor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='DeviceCredit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='DeviceETF',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='DeviceID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='DeviceMake',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='DeviceModel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='DeviceOS',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='DeviceSerialnumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='DeviceStorage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='DeviceType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='Insurance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='InternationalDataFeat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='InternationalTextFeat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='InternationalVoiceFeat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='LocationAddress1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='LocationAddress2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='LocationCity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='LocationState',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='LocationZip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='MobileAccessCharges',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='MobileDevice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='MobileIMEI',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='MobileSIMnumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='PlanLineNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='PlanName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='PlanType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='SiteName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='ThirdPartyAppCharge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='UpgradeEligibleDate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='UserEmail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='UserStatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='Username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='Vendor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='VendorNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='VoicePlanCharges',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='VoicePlanMins',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='WirelessNumber',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mappingobject',
            name='ban',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ban', to='OnBoard.uploadban'),
        ),
        migrations.AlterField(
            model_name='mappingobject',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='OnBoard.inventoryupload'),
        ),
    ]
