# Generated by Django 5.1.4 on 2025-02-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0017_mappingobject_accountnumber_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MappingObject',
            new_name='MappingObjectBan',
        ),
        migrations.AlterModelTable(
            name='mappingobjectban',
            table='MappingObjectBan',
        ),
    ]
