# Generated by Django 5.1.4 on 2025-02-10 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0018_rename_mappingobject_mappingobjectban_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadban',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='OnBoard.organizations'),
        ),
    ]
