# Generated by Django 5.1.4 on 2025-02-11 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0020_rename_costcenters_mappingobjectban_device_etf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mappingobjectban',
            old_name='PlanType',
            new_name='plan_type',
        ),
    ]
