# Generated by Django 5.1.4 on 2025-02-12 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0021_rename_plantype_mappingobjectban_plan_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('date_due', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('invoicenumber', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('duration', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('total_charges', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('company', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('Entry_type', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('vendor', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('sub_company', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('location', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('master_account', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('Total_current_charges', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('Remittance_Address', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('BillingName', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('Total_Amount_Due', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('banOnboarded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banOnboardedBase', to='OnBoard.onboardban')),
            ],
            options={
                'db_table': 'BaseDataTable',
            },
        ),
        migrations.CreateModel(
            name='BaselineDataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('wireless_number', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('user_name', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('plans', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('cost_center', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('account_charges_and_credits', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('monthly_charges', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('usage_and_purchase_charges', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('equipment_charges', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('surcharges_and_other_charges_credits', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('taxes_governmental_surcharges_and_fees', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('third_party_charges_includes_tax', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('total_charges', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('voice_plan_usage', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('messaging_usage', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('sub_company', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('catgory_obj', models.JSONField(default=dict)),
                ('banOnboarded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banOnboardedbase', to='OnBoard.onboardban')),
            ],
            options={
                'db_table': 'BaselineDataTable',
            },
        ),
        migrations.CreateModel(
            name='PdfDataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('wireless_number', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('user_name', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('plans', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('cost_center', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('account_charges_and_credits', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('monthly_charges', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('usage_and_purchase_charges', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('equipment_charges', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('surcharges_and_other_charges_credits', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('taxes_governmental_surcharges_and_fees', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('third_party_charges_includes_tax', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('total_charges', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('voice_plan_usage', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('messaging_usage', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('sub_company', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('banOnboarded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banOnboardedpdf', to='OnBoard.onboardban')),
            ],
            options={
                'db_table': 'PdfDataTable',
            },
        ),
        migrations.CreateModel(
            name='UniquePdfDataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('wireless_number', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('user_name', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('plans', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('cost_center', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('account_charges_and_credits', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('monthly_charges', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('usage_and_purchase_charges', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('equipment_charges', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('surcharges_and_other_charges_credits', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('taxes_governmental_surcharges_and_fees', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('third_party_charges_includes_tax', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('total_charges', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('voice_plan_usage', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('messaging_usage', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('sub_company', models.CharField(blank=True, default='NaN', max_length=255, null=True)),
                ('banOnboarded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banOnboardedunique', to='OnBoard.onboardban')),
            ],
            options={
                'db_table': 'UniquePdfDataTable',
            },
        ),
    ]
