# Generated by Django 5.1.4 on 2025-02-12 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0022_basedatatable_baselinedatatable_pdfdatatable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselinedatatable',
            name='banOnboarded',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banOnboardedbaseline', to='OnBoard.onboardban'),
        ),
        migrations.CreateModel(
            name='BatchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cust_Id', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('Sub_Id', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('Vendor_Number', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('Location_Code', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('Payment_Comments', models.CharField(blank=True, default='NA', max_length=255, null=True)),
                ('Payment_Number', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('Vendor_Name_1', models.CharField(blank=True, default='NA', max_length=255, null=True)),
                ('Vendor_Name_2', models.CharField(blank=True, default='NA', max_length=255, null=True)),
                ('Vendor_Address_1', models.CharField(blank=True, default='NA', max_length=255, null=True)),
                ('Vendor_Address_2', models.CharField(blank=True, default='NA', max_length=255, null=True)),
                ('Vendor_City', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('Vendor_State', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('Vendor_Zip', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('Vendor_Country', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('Vendor_Tax_Id', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('Vendor_Phone_Number', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('Customer_Vendor_Account_Number', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('Payment_Misc_1', models.CharField(blank=True, default='NA', max_length=255, null=True)),
                ('Invoice_Number', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('Total_Amount', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('Adjustment_Amount', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('Net_Amount', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('Due_Date', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('Invoice_Date', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('Invoice_Comments', models.CharField(blank=True, default='NA', max_length=255, null=True)),
                ('Invoice_Misc_1', models.CharField(blank=True, default='NA', max_length=255, null=True)),
                ('company', models.CharField(blank=True, default='NA', max_length=255, null=True)),
                ('remmitance_country', models.CharField(blank=True, default='NA', max_length=255, null=True)),
                ('month', models.CharField(default='NA', max_length=100, null=True)),
                ('year', models.CharField(default='NA', max_length=100, null=True)),
                ('email', models.CharField(default='NA', max_length=100, null=True)),
                ('sub_company_name', models.CharField(default='NA', max_length=100, null=True)),
                ('total_current_charges', models.CharField(default='NA', max_length=100, null=True)),
                ('duration', models.CharField(default='NA', max_length=100, null=True)),
                ('sub_company', models.CharField(default='NA', max_length=100, null=True)),
                ('billing_day', models.CharField(blank=True, max_length=255, null=True)),
                ('is_downloaded', models.CharField(blank=True, default='False', max_length=255, null=True)),
                ('approved', models.CharField(blank=True, default='Pending', max_length=255, null=True)),
                ('approved_changer', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Entry_type', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('master_account', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Total_Amount_Due', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('banOnboarded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banOnboardedbatchreport', to='OnBoard.onboardban')),
            ],
        ),
    ]
