# Generated by Django 5.1.4 on 2025-02-12 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0023_alter_baselinedatatable_banonboarded_batchreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfdatatable',
            old_name='surcharges_and_other_charges_credits',
            new_name='surcharges_and_other_charges_and_credits',
        ),
    ]
