# Generated by Django 5.1.4 on 2025-02-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0024_rename_surcharges_and_other_charges_credits_pdfdatatable_surcharges_and_other_charges_and_credits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basedatatable',
            old_name='BillingName',
            new_name='Billing_Name',
        ),
        migrations.RenameField(
            model_name='basedatatable',
            old_name='Remittance_Address',
            new_name='Remidence_Address',
        ),
        migrations.RenameField(
            model_name='basedatatable',
            old_name='Total_current_charges',
            new_name='Total_Current_Charges',
        ),
        migrations.RenameField(
            model_name='basedatatable',
            old_name='account_number',
            new_name='accountnumber',
        ),
    ]
