# Generated by Django 5.1.4 on 2025-02-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0026_rename_account_number_pdfdatatable_accountnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basedatatable',
            old_name='accountnumber',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='pdfdatatable',
            old_name='accountnumber',
            new_name='account_number',
        ),
    ]
