# Generated by Django 5.1.4 on 2025-02-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0027_rename_accountnumber_basedatatable_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basedatatable',
            name='account_number',
        ),
    ]
