# Generated by Django 5.1.4 on 2025-02-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0028_remove_basedatatable_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='account_number',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
    ]
