# Generated by Django 5.1.4 on 2025-02-12 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0029_basedatatable_account_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basedatatable',
            old_name='account_number',
            new_name='accountnumber',
        ),
    ]
