# Generated by Django 5.1.4 on 2025-02-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0030_rename_account_number_basedatatable_accountnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchreport',
            old_name='total_current_charges',
            new_name='Total_Current_Charges',
        ),
    ]
