# Generated by Django 5.1.4 on 2025-02-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0031_rename_total_current_charges_batchreport_total_current_charges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baselinedatatable',
            old_name='catgory_obj',
            new_name='category_object',
        ),
        migrations.RenameField(
            model_name='baselinedatatable',
            old_name='surcharges_and_other_charges_credits',
            new_name='surcharges_and_other_charges_and_credits',
        ),
    ]
