# Generated by Django 5.1.4 on 2025-02-17 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0032_rename_catgory_obj_baselinedatatable_category_object_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baselinedatatable',
            old_name='wireless_number',
            new_name='Wireless_number',
        ),
    ]
