# Generated by Django 5.1.4 on 2025-02-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0033_rename_wireless_number_baselinedatatable_wireless_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselinedatatable',
            name='company',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdfdatatable',
            name='company',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='company',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
    ]
