# Generated by Django 5.1.4 on 2025-02-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0034_baselinedatatable_company_pdfdatatable_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdatatable',
            name='vendor',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
    ]
