# Generated by Django 5.1.4 on 2025-02-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0035_pdfdatatable_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='vendor',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
    ]
