# Generated by Django 5.1.4 on 2025-02-19 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0036_uniquepdfdatatable_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselinedatatable',
            name='banOnboarded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banOnboardedbaseline', to='OnBoard.onboardban'),
        ),
    ]
