# Generated by Django 5.1.4 on 2025-02-19 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0037_alter_baselinedatatable_banonboarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedatatable',
            name='banOnboarded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banOnboardedBase', to='OnBoard.onboardban'),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='banOnboarded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banOnboardedpdf', to='OnBoard.onboardban'),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='banOnboarded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banOnboardedunique', to='OnBoard.onboardban'),
        ),
    ]
