# Generated by Django 5.1.4 on 2025-02-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0038_alter_basedatatable_banonboarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='entry_type',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
    ]
