# Generated by Django 5.1.4 on 2025-02-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0041_uniquepdfdatatable_cost_centers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='site_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('company', 'organization', 'site_name'), name='unique_location'),
        ),
    ]
