# Generated by Django 5.1.4 on 2025-02-27 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0043_uploadban_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventorybase', to='OnBoard.inventoryupload'),
        ),
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventoryunique', to='OnBoard.inventoryupload'),
        ),
    ]
