# Generated by Django 5.1.4 on 2025-02-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0044_basedatatable_inventory_uniquepdfdatatable_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadban',
            name='masteraccount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
