# Generated by Django 5.1.4 on 2025-02-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0046_uploadban_contract_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadban',
            name='contract_name',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
    ]
