# Generated by Django 5.1.4 on 2025-02-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0047_uploadban_contract_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardban',
            name='contract_file',
            field=models.FileField(null=True, upload_to='ban-contracts/'),
        ),
        migrations.AddField(
            model_name='onboardban',
            name='contract_name',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AddField(
            model_name='onboardban',
            name='remarks',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
    ]
