# Generated by Django 5.1.4 on 2025-02-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0048_onboardban_contract_file_onboardban_contract_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardban',
            name='contract_file',
        ),
        migrations.RemoveField(
            model_name='onboardban',
            name='contract_name',
        ),
        migrations.RemoveField(
            model_name='onboardban',
            name='remarks',
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='contract_file',
            field=models.FileField(null=True, upload_to='ban-contracts/'),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='contract_name',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='remarks',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
    ]
