# Generated by Django 5.1.4 on 2025-03-01 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_billtype'),
        ('OnBoard', '0049_remove_onboardban_contract_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='paymentType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dashboard.paymenttype'),
        ),
    ]
