# Generated by Django 5.1.4 on 2025-03-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0050_basedatatable_paymenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='auto_pay_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
