# Generated by Django 5.1.4 on 2025-03-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0051_basedatatable_auto_pay_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='billstatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='contract_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
