# Generated by Django 5.1.4 on 2025-03-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0052_basedatatable_billstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='Check',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
