# Generated by Django 5.1.4 on 2025-03-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0053_basedatatable_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselinedatatable',
            name='vendor',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
    ]
