# Generated by Django 5.1.4 on 2025-03-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0054_baselinedatatable_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='ECPD_Profile_ID',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
    ]
