# Generated by Django 5.1.4 on 2025-03-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0055_uniquepdfdatatable_ecpd_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='summary_file',
            field=models.FileField(blank=True, null=True, upload_to='view_summary_files/'),
        ),
    ]
