# Generated by Django 5.1.4 on 2025-03-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0056_basedatatable_summary_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadban',
            name='BillingDate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadban',
            name='Vendor_sub_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
