# Generated by Django 5.1.4 on 2025-03-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0057_uploadban_billingdate_uploadban_vendor_sub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadban',
            name='current_annual_review',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AddField(
            model_name='uploadban',
            name='previous_annual_review',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
    ]
