# Generated by Django 5.1.4 on 2025-03-04 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0061_alter_contract_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='OnBoard.organizations'),
        ),
    ]
