# Generated by Django 5.1.4 on 2025-03-04 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_billtype'),
        ('OnBoard', '0062_alter_contract_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dashboard.vendors'),
        ),
    ]
