# Generated by Django 5.1.4 on 2025-03-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_billtype'),
        ('OnBoard', '0063_contract_vendor'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contract',
            name='unique_contract',
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('organization', 'vendor'), name='unique_contract'),
        ),
    ]
