# Generated by Django 5.1.4 on 2025-03-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0064_remove_contract_unique_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
