# Generated by Django 5.1.4 on 2025-03-06 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0065_contract_contract_file_contract_contract_name_and_more'),
        ('View', '0002_alter_viewuploadbill_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingobjectban',
            name='viewupload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewupload', to='View.viewuploadbill'),
        ),
    ]
