# Generated by Django 5.1.4 on 2025-03-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0066_mappingobjectban_viewupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchreport',
            name='output_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='batchfiles/'),
        ),
        migrations.AlterModelTable(
            name='batchreport',
            table='BatchReport',
        ),
    ]
