# Generated by Django 5.1.4 on 2025-03-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_vendors_company_overview_vendors_customer_portal_url_and_more'),
        ('OnBoard', '0067_batchreport_output_file_alter_batchreport_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='favorite_vendors',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='Dashboard.vendors'),
        ),
    ]
