# Generated by Django 5.1.4 on 2025-03-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0069_uniquepdfdatatable_banuploaded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniquepdfdatatable',
            name='banOnboarded',
        ),
        migrations.RemoveField(
            model_name='uniquepdfdatatable',
            name='banUploaded',
        ),
        migrations.RemoveField(
            model_name='uniquepdfdatatable',
            name='inventory',
        ),
    ]
