# Generated by Django 5.1.4 on 2025-03-17 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0070_remove_uniquepdfdatatable_banonboarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='banOnboarded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboardedlines', to='OnBoard.onboardban'),
        ),
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='banUploaded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploadedlines', to='OnBoard.uploadban'),
        ),
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventorylines', to='OnBoard.inventoryupload'),
        ),
    ]
