# Generated by Django 5.1.4 on 2025-03-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0071_uniquepdfdatatable_banonboarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='cost_center_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='cost_center_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='deviceAmount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='deviceCredit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='cost_center',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
