# Generated by Django 5.1.4 on 2025-03-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0072_uniquepdfdatatable_cost_center_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='Billing_Address',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='month',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='pdf_filename',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='pdf_path',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='website',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='year',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
    ]
