# Generated by Django 5.1.4 on 2025-03-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0073_basedatatable_billing_address_basedatatable_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='account_charges_credits',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='charges',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='cost_center',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='item_category',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='item_description',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='plans',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='status',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='user_email',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdfdatatable',
            name='data_usage',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdfdatatable',
            name='group_number',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
    ]
