# Generated by Django 5.1.4 on 2025-03-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0074_basedatatable_account_charges_credits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basedatatable',
            name='account_charges_credits',
        ),
        migrations.RemoveField(
            model_name='basedatatable',
            name='cost_center',
        ),
        migrations.RemoveField(
            model_name='basedatatable',
            name='item_category',
        ),
        migrations.RemoveField(
            model_name='basedatatable',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='basedatatable',
            name='status',
        ),
        migrations.RemoveField(
            model_name='basedatatable',
            name='user_email',
        ),
        migrations.AddField(
            model_name='pdfdatatable',
            name='account_charges_credits',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdfdatatable',
            name='charges',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdfdatatable',
            name='location',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdfdatatable',
            name='status',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdfdatatable',
            name='user_email',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
    ]
