# Generated by Django 5.1.4 on 2025-03-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0076_basedatatable_item_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basedatatable',
            name='item_category',
        ),
        migrations.RemoveField(
            model_name='basedatatable',
            name='item_description',
        ),
        migrations.AddField(
            model_name='pdfdatatable',
            name='item_category',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdfdatatable',
            name='item_description',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
    ]
