# Generated by Django 5.1.4 on 2025-03-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0077_remove_basedatatable_item_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Sales_agent_details',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='Sales_agent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
