# Generated by Django 5.1.4 on 2025-03-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0078_alter_company_sales_agent_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='bill_date',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='data_usage',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='group_number',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='item_category',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='item_description',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
    ]
