# Generated by Django 5.1.4 on 2025-03-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0079_uniquepdfdatatable_bill_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselinedatatable',
            name='data_usage',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
    ]
