# Generated by Django 5.1.4 on 2025-03-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0080_baselinedatatable_data_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryupload',
            name='ban',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
