# Generated by Django 5.1.4 on 2025-03-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0081_alter_inventoryupload_ban'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselinedatatable',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baselinedatatable',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
