# Generated by Django 5.1.4 on 2025-03-25 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0082_baselinedatatable_is_draft_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
