# Generated by Django 5.1.4 on 2025-03-28 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0083_delete_contract'),
        ('View', '0011_viewuploadbill_ban'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselinedatatable',
            name='viewuploaded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewbaseline', to='View.viewuploadbill'),
        ),
        migrations.AddField(
            model_name='batchreport',
            name='viewuploaded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewbatch', to='View.viewuploadbill'),
        ),
        migrations.AddField(
            model_name='pdfdatatable',
            name='viewuploaded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewpdf', to='View.viewuploadbill'),
        ),
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='viewuploaded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewunique', to='View.viewuploadbill'),
        ),
    ]
