# Generated by Django 5.1.4 on 2025-03-29 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0084_baselinedatatable_viewuploaded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchreport',
            name='banOnboarded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banOnboardedbatchreport', to='OnBoard.onboardban'),
        ),
    ]
