# Generated by Django 5.1.4 on 2025-03-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0085_alter_batchreport_banonboarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselinedatatable',
            name='bill_date',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
    ]
