# Generated by Django 5.1.4 on 2025-04-15 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0087_basedatatable_created_basedatatable_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basedatatable',
            name='created',
        ),
        migrations.RemoveField(
            model_name='basedatatable',
            name='updated',
        ),
    ]
