# Generated by Django 5.1.4 on 2025-04-16 09:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0089_basedatatable_created_basedatatable_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselinedatatable',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baselinedatatable',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='batchreport',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),  # ✅
        ),
        migrations.AddField(
            model_name='batchreport',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='mappingobjectban',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),  # ✅
        ),
        migrations.AddField(
            model_name='mappingobjectban',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfdatatable',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),  # ✅
        ),
        migrations.AddField(
            model_name='pdfdatatable',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),  # ✅
        ),
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
