# Generated by Django 5.1.4 on 2025-04-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0090_baselinedatatable_created_baselinedatatable_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchreport',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mappingobjectban',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
