# Generated by Django 5.1.4 on 2025-04-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0091_alter_batchreport_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='Organization_logo'),
        ),
    ]
