# Generated by Django 5.1.4 on 2025-04-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0092_organizations_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='state',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
