# Generated by Django 5.1.4 on 2025-04-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_vendors_ratings'),
        ('OnBoard', '0093_organizations_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='vendors',
            field=models.ManyToManyField(blank=True, null=True, related_name='companies', to='Dashboard.vendors'),
        ),
    ]
