# Generated by Django 5.1.4 on 2025-04-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0094_alter_company_vendors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='vendors',
        ),
    ]
