# Generated by Django 5.1.4 on 2025-04-21 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0095_remove_company_vendors'),
        ('View', '0011_viewuploadbill_ban'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='viewuploaded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewbase', to='View.viewuploadbill'),
        ),
    ]
