# Generated by Django 5.1.4 on 2025-04-22 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0096_basedatatable_viewuploaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=1000)),
                ('Username', models.CharField(max_length=250)),
                ('Password', models.CharField(max_length=250)),
                ('Customer_Name', models.CharField(max_length=250)),
                ('Vendor', models.CharField(max_length=250)),
                ('Account_number', models.CharField(max_length=250)),
                ('User_email_id', models.CharField(max_length=250)),
                ('Automated', models.CharField(max_length=250)),
                ('On_Email', models.CharField(max_length=250)),
                ('banOnboarded', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banOnboardedportalinfo', to='OnBoard.onboardban')),
                ('banUploaded', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploadedportalinfo', to='OnBoard.uploadban')),
            ],
            options={
                'db_table': 'PortalInformation',
            },
        ),
    ]
