# Generated by Django 5.1.4 on 2025-04-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0097_portalinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizations',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
