# Generated by Django 5.1.4 on 2025-04-24 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0099_organizations_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='banUploaded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banUploadedBase', to='OnBoard.uploadban'),
        ),
        migrations.AddField(
            model_name='baselinedatatable',
            name='banUploaded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banUploadedbaseline', to='OnBoard.uploadban'),
        ),
    ]
