# Generated by Django 5.1.4 on 2025-04-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0100_basedatatable_banuploaded_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basedatatable',
            old_name='Billing_Address',
            new_name='BillingAdd',
        ),
        migrations.RenameField(
            model_name='basedatatable',
            old_name='Billing_Name',
            new_name='BillingAtn',
        ),
        migrations.RenameField(
            model_name='basedatatable',
            old_name='Remidence_Address',
            new_name='BillingCity',
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='BillingCountry',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='BillingDate',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='BillingName',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='BillingState',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='BillingZip',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='RemittanceAdd',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='RemittanceAtn',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='RemittanceCity',
            field=models.CharField(default='NaN', max_length=255),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='RemittanceCountry',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='RemittanceName',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='RemittanceNotes',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='RemittanceState',
            field=models.CharField(default='NaN', max_length=255),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='RemittanceZip',
            field=models.CharField(default='NaN', max_length=255),
        ),
    ]
