# Generated by Django 5.1.4 on 2025-04-25 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_vendors_ratings'),
        ('OnBoard', '0101_rename_billing_address_basedatatable_billingadd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='AccCharge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='BillingDay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='Billing_cycle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='ContractNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='ContractTerms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='CostCenter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='CostCenterNotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='CustomerOfRecord',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='Displaynotesonbillprocessing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='FoundAcc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='GlCode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='PO',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='POamt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='PayTerm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='Services',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='account_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='bantype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dashboard.bantype'),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='costcenterlevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dashboard.costcenterlevel'),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='costcenterstatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='costcentertype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dashboard.costcentertype'),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='invoicemethod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dashboard.invoicemethod'),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='payor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
