# Generated by Django 5.1.4 on 2025-04-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0102_basedatatable_acccharge_basedatatable_billingday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedatatable',
            name='bantype',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='costcenterlevel',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='costcentertype',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='invoicemethod',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='paymentType',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
    ]
