# Generated by Django 5.1.4 on 2025-04-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0103_alter_basedatatable_bantype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='Company_logos'),
        ),
    ]
