# Generated by Django 5.1.4 on 2025-04-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0104_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='current_annual_review',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='previous_annual_review',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='vendorCS',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
