# Generated by Django 5.1.4 on 2025-04-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0105_basedatatable_current_annual_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='vendor_alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
