# Generated by Django 5.1.4 on 2025-04-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0106_basedatatable_vendor_alias'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryupload',
            unique_together=set(),
        ),
    ]
