# Generated by Django 5.1.4 on 2025-04-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0107_alter_inventoryupload_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='banstatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
