# Generated by Django 5.1.4 on 2025-04-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0108_basedatatable_banstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='vendor_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
