# Generated by Django 5.1.4 on 2025-04-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0109_basedatatable_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='workbook_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
