# Generated by Django 5.1.4 on 2025-04-27 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0110_basedatatable_workbook_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchreport',
            name='banUploaded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banUploadedbatch', to='OnBoard.uploadban'),
        ),
    ]
