# Generated by Django 5.1.4 on 2025-04-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0111_batchreport_banuploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedatatable',
            name='bill_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
