# Generated by Django 5.1.4 on 2025-04-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0112_alter_basedatatable_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedatatable',
            name='bill_date',
            field=models.CharField(blank=True, default='NaN', max_length=255, null=True),
        ),
    ]
