# Generated by Django 5.1.4 on 2025-04-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0113_alter_basedatatable_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalinformation',
            name='Account_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='portalinformation',
            name='Automated',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='portalinformation',
            name='Customer_Name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='portalinformation',
            name='On_Email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='portalinformation',
            name='Password',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='portalinformation',
            name='URL',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='portalinformation',
            name='User_email_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='portalinformation',
            name='Username',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='portalinformation',
            name='Vendor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
