# Generated by Django 5.1.4 on 2025-05-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0117_alter_basedatatable_bill_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedatatable',
            name='bill_date',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='baselinedatatable',
            name='bill_date',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='bill_date',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
