# Generated by Django 5.1.4 on 2025-05-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0118_alter_basedatatable_bill_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselinedatatable',
            name='paymentstatus',
            field=models.CharField(blank=True, default='Pending', max_length=255, null=True),
        ),
    ]
