# Generated by Django 5.1.4 on 2025-06-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0119_baselinedatatable_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='category_object',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='User_status',
            field=models.CharField(blank=True, default='Active', max_length=255, null=True),
        ),
    ]
