# Generated by Django 5.1.4 on 2025-06-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0120_uniquepdfdatatable_category_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='category_object',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
