# Generated by Django 5.1.4 on 2025-06-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0121_alter_uniquepdfdatatable_category_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselinedatatable',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
