# Generated by Django 5.1.4 on 2025-06-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0122_baselinedatatable_is_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baselinedatatable',
            old_name='is_approved',
            new_name='is_baseline_approved',
        ),
        migrations.RenameField(
            model_name='uniquepdfdatatable',
            old_name='is_approved',
            new_name='is_baseline_approved',
        ),
    ]
