# Generated by Django 5.1.4 on 2025-06-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0123_rename_is_approved_baselinedatatable_is_baseline_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='is_baseline_approved',
            field=models.BooleanField(default=False),
        ),
    ]
