# Generated by Django 5.1.4 on 2025-06-18 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0124_basedatatable_is_baseline_approved'),
        ('View', '0014_paperbill_unique_paperbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='viewpapered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paperbase', to='View.paperbill'),
        ),
        migrations.AddField(
            model_name='baselinedatatable',
            name='viewpapered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paperbaseline', to='View.paperbill'),
        ),
        migrations.AddField(
            model_name='batchreport',
            name='viewpapered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paperbatch', to='View.paperbill'),
        ),
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='viewpapered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paperunique', to='View.paperbill'),
        ),
    ]
