# Generated by Django 5.1.4 on 2025-06-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0126_mappingobjectban_bill_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedatatable',
            name='billstatus',
            field=models.CharField(blank=True, default='Active', max_length=255, null=True),
        ),
    ]
