# Generated by Django 5.1.4 on 2025-06-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0127_alter_basedatatable_billstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingobjectban',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
