# Generated by Django 5.1.4 on 2025-06-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0128_alter_mappingobjectban_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchreport',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
