# Generated by Django 5.1.4 on 2025-06-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0129_batchreport_remark_uniquepdfdatatable_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchreport',
            name='remark',
        ),
        migrations.AddField(
            model_name='baselinedatatable',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
