# Generated by Django 5.1.4 on 2025-06-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0130_remove_batchreport_remark_baselinedatatable_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='baseline_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
