# Generated by Django 5.1.4 on 2025-06-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0131_basedatatable_baseline_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='batch_approved',
            field=models.CharField(blank=True, default='Pending', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='batch_approved_changer',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
