# Generated by Django 5.1.4 on 2025-06-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0132_basedatatable_batch_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='net_amount',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
