# Generated by Django 5.1.4 on 2025-07-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0133_basedatatable_net_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselinedatatable',
            name='data_allotment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='baselinedatatable',
            name='mifi',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='baselinedatatable',
            name='plan_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='baselinedatatable',
            name='plan_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='baselinedatatable',
            name='smartphone',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='baselinedatatable',
            name='tablet_computer',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='baselinedatatable',
            name='wearables',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='data_allotment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='mifi',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='plan_fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='smartphone',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='tablet_computer',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='wearables',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='plan_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
