# Generated by Django 5.1.4 on 2025-07-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0134_baselinedatatable_data_allotment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='batch_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='batchfiles/'),
        ),
    ]
