# Generated by Django 5.1.4 on 2025-07-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0137_alter_basedatatable_billingcountry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedatatable',
            name='BillingCountry',
            field=models.CharField(blank=True, default='USA', max_length=255, null=True),
        ),
    ]
