# Generated by Django 5.1.4 on 2025-07-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0138_alter_basedatatable_billingcountry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedatatable',
            name='BillingCountry',
            field=models.CharField(blank=True, default='United States', max_length=255, null=True),
        ),
    ]
