# Generated by Django 5.1.4 on 2025-08-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0139_alter_basedatatable_billingcountry'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdatatable',
            name='item_charges',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
