# Generated by Django 5.1.4 on 2025-08-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0140_pdfdatatable_item_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselinedatatable',
            name='VendorNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='VendorNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
