# Generated by Django 5.1.4 on 2025-08-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0141_baselinedatatable_vendornumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
