# Generated by Django 5.1.4 on 2025-08-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0142_alter_links_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardban',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
