# Generated by Django 5.1.4 on 2025-08-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0143_onboardban_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardban',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
