# Generated by Django 5.1.4 on 2025-08-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0144_onboardban_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='is_production',
            field=models.BooleanField(default=False),
        ),
    ]
