# Generated by Django 5.1.4 on 2025-08-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0145_basedatatable_is_production'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basedatatable',
            name='inventory',
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='variance',
            field=models.FloatField(default=5),
        ),
    ]
