# Generated by Django 5.1.4 on 2025-08-27 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0146_remove_basedatatable_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='inventort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventorybase', to='OnBoard.inventoryupload'),
        ),
    ]
