# Generated by Django 5.1.4 on 2025-08-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0147_basedatatable_inventort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basedatatable',
            old_name='inventort',
            new_name='inventory',
        ),
    ]
