# Generated by Django 5.1.4 on 2025-08-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0148_rename_inventort_basedatatable_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardban',
            name='variance',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='uploadban',
            name='variance',
            field=models.FloatField(default=5),
        ),
    ]
