# Generated by Django 5.1.4 on 2025-09-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0149_onboardban_variance_uploadban_variance'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='is_baseline_replaced',
            field=models.BooleanField(default=False),
        ),
    ]
