# Generated by Django 5.1.4 on 2025-09-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0150_basedatatable_is_baseline_replaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='Location_code',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
