# Generated by Django 5.1.4 on 2025-09-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0151_uniquepdfdatatable_location_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='Domain',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='Phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='other_domains',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='tax_id',
            field=models.CharField(max_length=255),
        ),
    ]
