# Generated by Django 5.1.4 on 2025-09-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0152_alter_organizations_domain_alter_organizations_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardban',
            name='contract_file',
            field=models.FileField(null=True, upload_to='ban-contracts/'),
        ),
        migrations.AddField(
            model_name='onboardban',
            name='contract_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
