# Generated by Django 5.1.4 on 2025-09-19 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0153_onboardban_contract_file_onboardban_contract_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basedatatable',
            name='contract_file',
        ),
        migrations.RemoveField(
            model_name='basedatatable',
            name='contract_name',
        ),
    ]
