# Generated by Django 5.1.4 on 2025-10-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0154_remove_basedatatable_contract_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='batch_approved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
