# Generated by Django 5.1.4 on 2025-10-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0155_basedatatable_batch_approved_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basedatatable',
            name='batch_approved_date',
        ),
        migrations.AddField(
            model_name='basedatatable',
            name='bill_approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
