# Generated by Django 5.1.4 on 2025-10-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0156_remove_basedatatable_batch_approved_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='BillingCurrency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
