# Generated by Django 5.1.4 on 2025-10-15 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0158_banhistory_wirelesshistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wirelesshistory',
            name='banOnboarded',
        ),
        migrations.RemoveField(
            model_name='wirelesshistory',
            name='banUploaded',
        ),
        migrations.DeleteModel(
            name='BanHistory',
        ),
        migrations.DeleteModel(
            name='WirelessHistory',
        ),
    ]
