# Generated by Django 5.1.4 on 2025-10-28 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0159_remove_wirelesshistory_banonboarded_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_bills', to=settings.AUTH_USER_MODEL),
        ),
    ]
