# Generated by Django 5.1.4 on 2025-11-07 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0160_basedatatable_uploaded_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ban_updated_by_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wireless_updated_by_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
