# Generated by Django 5.1.4 on 2025-11-07 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0161_basedatatable_last_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basedatatable',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='uniquepdfdatatable',
            name='last_updated_by',
        ),
    ]
