# Generated by Django 5.1.4 on 2025-11-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0162_remove_basedatatable_last_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingobjectban',
            name='monthly_charges',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
