# Generated by Django 5.1.4 on 2025-11-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0163_mappingobjectban_monthly_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquepdfdatatable',
            name='accessories',
            field=models.JSONField(default=list),
        ),
    ]
