# Generated by Django 5.1.4 on 2025-12-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0164_uniquepdfdatatable_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatatable',
            name='check_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
