# Generated by Django 5.1.4 on 2025-12-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0165_basedatatable_check_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingobjectban',
            name='monthly_charges',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
