# Generated by Django 5.1.4 on 2025-12-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0166_alter_mappingobjectban_monthly_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedatatable',
            name='BillingCurrency',
            field=models.CharField(blank=True, default='USD', max_length=255, null=True),
        ),
    ]
