# Generated by Django 5.1.4 on 2025-12-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0167_alter_basedatatable_billingcurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedatatable',
            name='BillingCurrency',
            field=models.CharField(default='USD', max_length=255),
        ),
    ]
