# Generated by Django 5.1.4 on 2025-12-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0168_alter_basedatatable_billingcurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='Company_logos/'),
        ),
    ]
