# Generated by Django 5.1.4 on 2026-01-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0169_alter_company_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='mobile_status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='upgrade_eligible_date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
