# Generated by Django 5.1.4 on 2026-01-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0170_rename_mobile_status_location_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='DM_DID_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='DM_email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
