# Generated by Django 5.1.4 on 2026-01-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0171_alter_organizations_dm_did_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedatatable',
            name='BillingAdd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='BillingAtn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='BillingCity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='BillingDate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='BillingName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='BillingState',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='BillingZip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='Entry_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='RemittanceAdd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='RemittanceAtn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='RemittanceCity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='RemittanceName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='RemittanceNotes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='RemittanceState',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='RemittanceZip',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='Total_Amount_Due',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='Total_Current_Charges',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='accountnumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='banstatus',
            field=models.CharField(default='Active', max_length=255),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='bantype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='bill_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='billstatus',
            field=models.CharField(default='Active', max_length=255),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='charges',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='company',
            field=models.CharField(default='OneSmarter', max_length=255),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='costcenterlevel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='costcentertype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='date_due',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='invoicemethod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='invoicenumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='master_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='month',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='paymentType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='pdf_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='pdf_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='plans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='sub_company',
            field=models.CharField(default='OSI', max_length=255),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='total_charges',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='vendor',
            field=models.CharField(default='Verizon', max_length=255),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='basedatatable',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='baselinedatatable',
            name='Wireless_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='baselinedatatable',
            name='account_charges_and_credits',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='baselinedatatable',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='baselinedatatable',
            name='bill_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='baselinedatatable',
            name='company',
            field=models.CharField(default='OneSmarter', max_length=255),
        ),
        migrations.AlterField(
            model_name='baselinedatatable',
            name='cost_center',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='baselinedatatable',
            name='data_usage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='baselinedatatable',
            name='equipment_charges',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='baselinedatatable',
            name='messaging_usage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='baselinedatatable',
            name='monthly_charges',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='baselinedatatable',
            name='plans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='baselinedatatable',
            name='sub_company',
            field=models.CharField(default='OSI', max_length=255),
        ),
        migrations.AlterField(
            model_name='baselinedatatable',
            name='surcharges_and_other_charges_and_credits',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='baselinedatatable',
            name='taxes_governmental_surcharges_and_fees',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='baselinedatatable',
            name='third_party_charges_includes_tax',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='baselinedatatable',
            name='total_charges',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='baselinedatatable',
            name='usage_and_purchase_charges',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='baselinedatatable',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='baselinedatatable',
            name='vendor',
            field=models.CharField(default='Verizon', max_length=255),
        ),
        migrations.AlterField(
            model_name='baselinedatatable',
            name='voice_plan_usage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='Adjustment_Amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='Cust_Id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='Customer_Vendor_Account_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='Due_Date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='Invoice_Comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='Invoice_Date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='Invoice_Misc_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='Invoice_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='Location_Code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='Net_Amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='Payment_Comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='Payment_Misc_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='Payment_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='Sub_Id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='Total_Amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='Total_Current_Charges',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='Vendor_Address_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='Vendor_Address_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='Vendor_City',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='Vendor_Country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='Vendor_Name_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='Vendor_Name_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='Vendor_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='Vendor_Phone_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='Vendor_State',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='Vendor_Tax_Id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='Vendor_Zip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='company',
            field=models.CharField(default='OneSmarter', max_length=255),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='month',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='remmitance_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='sub_company',
            field=models.CharField(default='OSI', max_length=255),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='sub_company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchreport',
            name='year',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mappingobjectban',
            name='vendor',
            field=models.CharField(default='Verizon', max_length=255),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='account_charges_and_credits',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='account_charges_credits',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='charges',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='company',
            field=models.CharField(default='OneSmarter', max_length=255),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='cost_center',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='data_usage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='equipment_charges',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='group_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='item_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='item_charges',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='item_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='messaging_usage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='monthly_charges',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='plans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='sub_company',
            field=models.CharField(default='OSI', max_length=255),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='surcharges_and_other_charges_and_credits',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='taxes_governmental_surcharges_and_fees',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='third_party_charges_includes_tax',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='total_charges',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='usage_and_purchase_charges',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='user_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='vendor',
            field=models.CharField(default='Verizon', max_length=255),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='voice_plan_usage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdfdatatable',
            name='wireless_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='Device_ETF',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='Devices_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='Devices_device_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='Devices_make',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='Devices_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='Devices_os',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='Devices_serial_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='Devices_storage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='ECPD_Profile_ID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='Location_address_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='Location_address_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='Location_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='Location_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='Location_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='Location_zip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='Plan_line_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='Plan_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='User_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='User_status',
            field=models.CharField(default='Active', max_length=255),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='account_charges_and_credits',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='bill_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='company',
            field=models.CharField(default='OneSmarter', max_length=255),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='cost_centers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='data_plan_allotment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='data_plan_charges',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='data_usage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='entry_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='equipment_charges',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='group_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='imei_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='insurance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='international_data_feat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='international_text_feat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='international_voice_feat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='item_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='item_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='messaging_usage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='mobile_access_charge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='mobile_device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='mobile_sim_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='monthly_charges',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='plans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='site_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='sub_company',
            field=models.CharField(default='OSI', max_length=255),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='surcharges_and_other_charges_credits',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='taxes_governmental_surcharges_and_fees',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='third_party_app_charge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='third_party_charges_includes_tax',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='total_charges',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='usage_and_purchase_charges',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='vendor',
            field=models.CharField(default='Verizon', max_length=255),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='voice_plan_charges',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='voice_plan_mins',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='voice_plan_usage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='wireless_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
