# Generated by Django 5.1.4 on 2026-01-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0172_alter_basedatatable_billingadd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingobjectban',
            name='User_status',
            field=models.CharField(default='Active', max_length=255),
        ),
    ]
