# Generated by Django 5.1.4 on 2026-01-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0173_alter_mappingobjectban_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingobjectban',
            name='User_status',
            field=models.CharField(default='Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepdfdatatable',
            name='User_status',
            field=models.CharField(default='Active', max_length=255, null=True),
        ),
    ]
