# Generated by Django 5.1.4 on 2026-01-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0174_alter_mappingobjectban_user_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.CharField(default='Active', max_length=255),
        ),
    ]
