# Generated by Django 5.1.4 on 2026-01-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnBoard', '0175_alter_location_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingobjectban',
            name='total_charges',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
